# Generated by Django 5.1.4 on 2026-01-04 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Unique configuration key identifier', max_length=255, unique=True)),
                ('value', models.JSONField(help_text='Configuration value stored as JSON (supports strings, numbers, booleans, objects, arrays)')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('object', 'Object'), ('array', 'Array')], default='string', help_text='Type of the configuration value', max_length=20)),
                ('category', models.CharField(blank=True, db_index=True, help_text="Category or group name for organizing configurations (e.g., 'email', 'api', 'ui')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of what this configuration does')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this configuration is active and should be used')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the configuration was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the configuration was last updated')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_configs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Global Configuration',
                'verbose_name_plural': 'Global Configurations',
                'db_table': 'app_config_globalconfig',
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='app_config__categor_d0a95a_idx'), models.Index(fields=['key', 'is_active'], name='app_config__key_9c4bf9_idx')],
            },
        ),
    ]
