# Generated by Django 5.1.4 on 2026-01-09 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Unique identifier for the provider, e.g., 'aws_china'", max_length=100, unique=True)),
                ('provider_type', models.CharField(choices=[('aws', 'AWS'), ('huawei', 'Huawei Cloud'), ('alibaba', 'Alibaba Cloud'), ('azure', 'Azure')], help_text='Cloud provider type', max_length=20)),
                ('display_name', models.CharField(help_text="Display name for the provider, e.g., 'AWS China'", max_length=200)),
                ('config', models.JSONField(help_text='Authentication configuration stored as JSON')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this provider is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cloud_providers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cloud_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cloud Provider',
                'verbose_name_plural': 'Cloud Providers',
                'db_table': 'cloud_billing_provider',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BillingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text="Billing period in YYYY-MM format, e.g., '2025-01'", max_length=7)),
                ('hour', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23)], help_text='Collection hour, 0-23')),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total cost', max_digits=20)),
                ('currency', models.CharField(default='USD', help_text="Currency code, e.g., 'USD', 'CNY'", max_length=10)),
                ('service_costs', models.JSONField(default=dict, help_text="Service cost breakdown, format: {'service_name': cost, ...}")),
                ('account_id', models.CharField(blank=True, help_text='Account ID', max_length=100)),
                ('collected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_data', to='cloud_billing.cloudprovider')),
            ],
            options={
                'verbose_name': 'Billing Data',
                'verbose_name_plural': 'Billing Data',
                'db_table': 'cloud_billing_data',
                'ordering': ['-period', '-hour'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Absolute cost threshold', max_digits=20, null=True)),
                ('growth_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Growth percentage threshold, e.g., 5.0 means 5%', max_digits=5, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this alert rule is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alert_rules', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_alert_rules', to=settings.AUTH_USER_MODEL)),
                ('provider', models.OneToOneField(help_text='Cloud provider for this alert rule', on_delete=django.db.models.deletion.CASCADE, related_name='alert_rule', to='cloud_billing.cloudprovider')),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
                'db_table': 'cloud_billing_alert_rule',
            },
        ),
        migrations.CreateModel(
            name='AlertRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_cost', models.DecimalField(decimal_places=2, help_text='Current hour cost', max_digits=20)),
                ('previous_cost', models.DecimalField(decimal_places=2, help_text='Previous hour cost', max_digits=20)),
                ('increase_cost', models.DecimalField(decimal_places=2, help_text='Cost increase amount', max_digits=20)),
                ('increase_percent', models.DecimalField(decimal_places=2, help_text='Cost increase percentage', max_digits=5)),
                ('currency', models.CharField(help_text='Currency code', max_length=10)),
                ('alert_message', models.TextField(help_text='Alert message content')),
                ('webhook_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('webhook_response', models.JSONField(blank=True, help_text='Webhook response content', null=True)),
                ('webhook_error', models.TextField(blank=True, help_text='Webhook error message if failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alert_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_records', to='cloud_billing.alertrule')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_records', to='cloud_billing.cloudprovider')),
            ],
            options={
                'verbose_name': 'Alert Record',
                'verbose_name_plural': 'Alert Records',
                'db_table': 'cloud_billing_alert_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cloudprovider',
            index=models.Index(fields=['provider_type', 'is_active'], name='cloud_billi_provide_20ccce_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudprovider',
            index=models.Index(fields=['name'], name='cloud_billi_name_515568_idx'),
        ),
        migrations.AddIndex(
            model_name='billingdata',
            index=models.Index(fields=['provider', 'period', 'hour'], name='cloud_billi_provide_40a62c_idx'),
        ),
        migrations.AddIndex(
            model_name='billingdata',
            index=models.Index(fields=['period', 'hour'], name='cloud_billi_period_3543ce_idx'),
        ),
        migrations.AddIndex(
            model_name='billingdata',
            index=models.Index(fields=['collected_at'], name='cloud_billi_collect_9804cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='billingdata',
            unique_together={('provider', 'period', 'hour')},
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['provider', 'is_active'], name='cloud_billi_provide_eeed97_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrecord',
            index=models.Index(fields=['provider', 'created_at'], name='cloud_billi_provide_1faf11_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrecord',
            index=models.Index(fields=['webhook_status'], name='cloud_billi_webhook_33e7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrecord',
            index=models.Index(fields=['created_at'], name='cloud_billi_created_4b905b_idx'),
        ),
    ]
