# Generated by Django 5.1.4 on 2026-02-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_billing', '0006_alter_billingdata_total_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudprovider',
            name='config',
            field=models.JSONField(help_text="Authentication and optional metadata as JSON. For alert notifications, set config['notification'] = {type: 'webhook'|'email', channel_uuid: '<uuid>', email_to: ['a@b.com', ...]} (email_to is an array of strings, used when type is 'email')."),
        ),
    ]
