# Generated by Django 5.1.4 on 2026-02-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="taskexecution",
            new_name="task_manage_module_078711_idx",
            old_name="task_manage_module_status_idx",
        ),
        migrations.RenameIndex(
            model_name="taskexecution",
            new_name="task_manage_task_na_ed3826_idx",
            old_name="task_manage_task_name_status_idx",
        ),
        migrations.RenameIndex(
            model_name="taskexecution",
            new_name="task_manage_created_ee3431_idx",
            old_name="task_manage_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="taskexecution",
            new_name="task_manage_status_da7bdb_idx",
            old_name="task_manage_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="taskexecution",
            new_name="task_manage_module_62e132_idx",
            old_name="task_manage_module_created_idx",
        ),
        migrations.RenameIndex(
            model_name="taskexecution",
            new_name="task_manage_created_bad7a4_idx",
            old_name="task_manage_user_status_idx",
        ),
        migrations.RenameIndex(
            model_name="taskexecution",
            new_name="task_manage_created_fc144b_idx",
            old_name="task_manage_user_created_idx",
        ),
    ]
