"""Settings for quotation documents, PDF rendering, and Feishu Drive."""

import os

from .accounts import FRONTEND_URL


STORAGE_ROOT = os.getenv("STORAGE_ROOT", "/opt/storage")

QUOTATION_STORAGE = os.getenv(
    "QUOTATION_STORAGE",
    os.path.join(STORAGE_ROOT, "quotation"),
)

FEISHU_APP_ID = os.getenv("FEISHU_APP_ID", "")
FEISHU_APP_SECRET = os.getenv("FEISHU_APP_SECRET", "")
FEISHU_BASE_URL = os.getenv(
    "FEISHU_BASE_URL",
    os.getenv("FEISHU_AUTH_BASE_URL", "https://open.feishu.cn"),
)
FEISHU_WEB_BASE_URL = os.getenv(
    "FEISHU_WEB_BASE_URL",
    os.getenv("FEISHU_APPROVAL_BASE_URL", "https://feishu.cn"),
)
FEISHU_OAUTH_REDIRECT_URI = os.getenv(
    "FEISHU_OAUTH_REDIRECT_URI",
    (
        f"{FRONTEND_URL.rstrip('/')}"
        "/api/v1/quotation/feishu/oauth/callback"
    ),
)
FEISHU_OAUTH_SCOPES = os.getenv(
    "FEISHU_OAUTH_SCOPES",
    "drive:drive drive:file drive:file:upload drive:file:download "
    "drive:export:readonly docs:document:export search:docs:read "
    "offline_access",
)
FEISHU_TEST_FOLDER_TOKEN = os.getenv("FEISHU_TEST_FOLDER_TOKEN", "")
QUOTATION_FEISHU_ARCHIVE_FOLDER_URL = os.getenv(
    "QUOTATION_FEISHU_ARCHIVE_FOLDER_URL",
    os.getenv("FEISHU_ARCHIVE_FOLDER_URL", ""),
)
QUOTATION_FEISHU_ARCHIVE_FOLDER_TOKEN = os.getenv(
    "QUOTATION_FEISHU_ARCHIVE_FOLDER_TOKEN",
    os.getenv("FEISHU_ARCHIVE_FOLDER_TOKEN", FEISHU_TEST_FOLDER_TOKEN),
)

QUOTATION_MAX_UPLOAD_BYTES = int(
    os.getenv("QUOTATION_MAX_UPLOAD_BYTES", str(50 * 1024 * 1024))
)
QUOTATION_ALLOWED_EXTENSIONS = (".xlsx", ".pdf")
QUOTATION_MAX_PDF_HTML_BYTES = int(
    os.getenv("QUOTATION_MAX_PDF_HTML_BYTES", str(5 * 1024 * 1024))
)
QUOTATION_MAX_PDF_XLSX_BYTES = int(
    os.getenv("QUOTATION_MAX_PDF_XLSX_BYTES", str(6 * 1024 * 1024))
)
QUOTATION_MAX_XLSX_EXPANDED_BYTES = int(
    os.getenv(
        "QUOTATION_MAX_XLSX_EXPANDED_BYTES",
        str(50 * 1024 * 1024),
    )
)
QUOTATION_MAX_PDF_BYTES = int(
    os.getenv("QUOTATION_MAX_PDF_BYTES", str(20 * 1024 * 1024))
)
GOTENBERG_URL = os.getenv("GOTENBERG_URL", "http://gotenberg:3000")
GOTENBERG_TIMEOUT_SECONDS = float(
    os.getenv("GOTENBERG_TIMEOUT_SECONDS", "30")
)

QUOTATION_SECURITY_ALERT_OWNER = os.getenv(
    "QUOTATION_SECURITY_ALERT_OWNER",
    "Quote Desk administrators",
)
QUOTATION_SECURITY_ALERT_RUNBOOK_BASE_URL = os.getenv(
    "QUOTATION_SECURITY_ALERT_RUNBOOK_BASE_URL",
    "/docs/quote-desk/security-alerts",
)
QUOTATION_SECURITY_DENIAL_THRESHOLD = int(
    os.getenv("QUOTATION_SECURITY_DENIAL_THRESHOLD", "5")
)
QUOTATION_SECURITY_DENIAL_WINDOW_MINUTES = int(
    os.getenv("QUOTATION_SECURITY_DENIAL_WINDOW_MINUTES", "5")
)
QUOTATION_SECURITY_DOWNLOAD_THRESHOLD = int(
    os.getenv("QUOTATION_SECURITY_DOWNLOAD_THRESHOLD", "20")
)
QUOTATION_SECURITY_DOWNLOAD_WINDOW_MINUTES = int(
    os.getenv("QUOTATION_SECURITY_DOWNLOAD_WINDOW_MINUTES", "10")
)
QUOTATION_SECURITY_ENUMERATION_THRESHOLD = int(
    os.getenv("QUOTATION_SECURITY_ENUMERATION_THRESHOLD", "10")
)
QUOTATION_SECURITY_ENUMERATION_WINDOW_MINUTES = int(
    os.getenv("QUOTATION_SECURITY_ENUMERATION_WINDOW_MINUTES", "5")
)
QUOTATION_SECURITY_SYNC_FAILURE_THRESHOLD = int(
    os.getenv("QUOTATION_SECURITY_SYNC_FAILURE_THRESHOLD", "3")
)
QUOTATION_SECURITY_SYNC_FAILURE_WINDOW_MINUTES = int(
    os.getenv("QUOTATION_SECURITY_SYNC_FAILURE_WINDOW_MINUTES", "30")
)
QUOTATION_AUDIT_RETENTION_DAYS = int(
    os.getenv("QUOTATION_AUDIT_RETENTION_DAYS", "365")
)
QUOTATION_AUDIT_EXPORT_MAX_ROWS = int(
    os.getenv("QUOTATION_AUDIT_EXPORT_MAX_ROWS", "50000")
)
QUOTATION_STORAGE_ROUTER_ENABLED = (
    os.getenv("QUOTATION_STORAGE_ROUTER_ENABLED", "true").lower() == "true"
)
QUOTATION_DOCUMENT_REPLICA_ENABLED = (
    os.getenv("QUOTATION_DOCUMENT_REPLICA_ENABLED", "true").lower()
    == "true"
)
QUOTATION_FEISHU_DIRECT_LINK_MODE = os.getenv(
    "QUOTATION_FEISHU_DIRECT_LINK_MODE",
    "trusted",
)
