"""Settings for quotation documents, PDF rendering, and Feishu Drive."""

import os

from .accounts import FRONTEND_URL

STORAGE_ROOT = os.getenv("STORAGE_ROOT", "/opt/storage")

QUOTATION_STORAGE = os.getenv(
    "QUOTATION_STORAGE",
    os.path.join(STORAGE_ROOT, "quotation"),
)

FEISHU_APP_ID = os.getenv("FEISHU_APP_ID", "")
FEISHU_APP_SECRET = os.getenv("FEISHU_APP_SECRET", "")
FEISHU_BASE_URL = os.getenv(
    "FEISHU_BASE_URL",
    os.getenv("FEISHU_AUTH_BASE_URL", "https://open.feishu.cn"),
)
FEISHU_WEB_BASE_URL = os.getenv(
    "FEISHU_WEB_BASE_URL",
    os.getenv("FEISHU_APPROVAL_BASE_URL", "https://feishu.cn"),
)
FEISHU_OAUTH_REDIRECT_URI = os.getenv(
    "FEISHU_OAUTH_REDIRECT_URI",
    (f"{FRONTEND_URL.rstrip('/')}" "/api/v1/quotation/feishu/oauth/callback"),
)
FEISHU_OAUTH_SCOPES = os.getenv(
    "FEISHU_OAUTH_SCOPES",
    "drive:drive drive:file drive:file:upload drive:file:download "
    "drive:export:readonly docs:document:export search:docs:read "
    "offline_access",
)
FEISHU_TEST_FOLDER_TOKEN = os.getenv("FEISHU_TEST_FOLDER_TOKEN", "")
QUOTATION_FEISHU_ARCHIVE_FOLDER_URL = os.getenv(
    "QUOTATION_FEISHU_ARCHIVE_FOLDER_URL",
    os.getenv("FEISHU_ARCHIVE_FOLDER_URL", ""),
)
QUOTATION_FEISHU_ARCHIVE_FOLDER_TOKEN = os.getenv(
    "QUOTATION_FEISHU_ARCHIVE_FOLDER_TOKEN",
    os.getenv("FEISHU_ARCHIVE_FOLDER_TOKEN", FEISHU_TEST_FOLDER_TOKEN),
)

QUOTATION_MAX_UPLOAD_BYTES = int(
    os.getenv("QUOTATION_MAX_UPLOAD_BYTES", str(50 * 1024 * 1024))
)
QUOTATION_UPLOAD_CHUNK_BYTES = int(
    os.getenv("QUOTATION_UPLOAD_CHUNK_BYTES", str(1024 * 1024))
)
QUOTATION_ALLOWED_EXTENSIONS = (".xlsx", ".pdf")
QUOTATION_PUBLIC_ATTACHMENT_EXTENSIONS = (
    ".pdf",
    ".doc",
    ".docx",
    ".xls",
    ".xlsx",
)
QUOTATION_ALLOWED_CURRENCIES = tuple(
    currency.strip().upper()
    for currency in os.getenv(
        "QUOTATION_ALLOWED_CURRENCIES",
        "USD,CNY,EUR,GBP,MYR,HKD",
    ).split(",")
    if currency.strip()
)
QUOTATION_MAX_ITEMS = int(os.getenv("QUOTATION_MAX_ITEMS", "200"))
QUOTATION_MAX_ITEM_DESCRIPTION_LENGTH = int(
    os.getenv("QUOTATION_MAX_ITEM_DESCRIPTION_LENGTH", "4000")
)
QUOTATION_MAX_REMARKS_LENGTH = int(
    os.getenv("QUOTATION_MAX_REMARKS_LENGTH", "10000")
)
QUOTATION_MAX_SIGNATURE_LENGTH = int(
    os.getenv("QUOTATION_MAX_SIGNATURE_LENGTH", str(3 * 1024 * 1024))
)
QUOTATION_XLSX_MAX_ENTRIES = int(
    os.getenv("QUOTATION_XLSX_MAX_ENTRIES", "2048")
)
QUOTATION_XLSX_MAX_ENTRY_BYTES = int(
    os.getenv("QUOTATION_XLSX_MAX_ENTRY_BYTES", str(64 * 1024 * 1024))
)
QUOTATION_XLSX_MAX_EXPANDED_BYTES = int(
    os.getenv("QUOTATION_XLSX_MAX_EXPANDED_BYTES", str(128 * 1024 * 1024))
)
QUOTATION_XLSX_MAX_COMPRESSION_RATIO = int(
    os.getenv("QUOTATION_XLSX_MAX_COMPRESSION_RATIO", "200")
)
QUOTATION_XLSX_MAX_WORKSHEETS = int(
    os.getenv("QUOTATION_XLSX_MAX_WORKSHEETS", "20")
)
QUOTATION_XLSX_MAX_ROWS = int(os.getenv("QUOTATION_XLSX_MAX_ROWS", "5000"))
QUOTATION_XLSX_MAX_COLUMNS = int(
    os.getenv("QUOTATION_XLSX_MAX_COLUMNS", "200")
)
QUOTATION_XLSX_PARSED_COLUMNS = int(
    os.getenv("QUOTATION_XLSX_PARSED_COLUMNS", "20")
)
QUOTATION_XLSX_MAX_SHARED_STRINGS_BYTES = int(
    os.getenv(
        "QUOTATION_XLSX_MAX_SHARED_STRINGS_BYTES",
        str(32 * 1024 * 1024),
    )
)
QUOTATION_XLSX_MAX_SHARED_STRINGS = int(
    os.getenv("QUOTATION_XLSX_MAX_SHARED_STRINGS", "100000")
)
QUOTATION_PARSE_SOFT_TIME_LIMIT_SECONDS = int(
    os.getenv("QUOTATION_PARSE_SOFT_TIME_LIMIT_SECONDS", "90")
)
QUOTATION_PARSE_TIME_LIMIT_SECONDS = int(
    os.getenv("QUOTATION_PARSE_TIME_LIMIT_SECONDS", "120")
)
QUOTATION_MAX_TEMPLATE_BYTES = int(
    os.getenv("QUOTATION_MAX_TEMPLATE_BYTES", str(6 * 1024 * 1024))
)
QUOTATION_MAX_TEMPLATE_EXPANDED_BYTES = int(
    os.getenv(
        "QUOTATION_MAX_TEMPLATE_EXPANDED_BYTES",
        str(50 * 1024 * 1024),
    )
)
QUOTATION_MAX_PDF_BYTES = int(
    os.getenv("QUOTATION_MAX_PDF_BYTES", str(20 * 1024 * 1024))
)
QUOTATION_MAX_SIGNATURE_BYTES = int(
    os.getenv("QUOTATION_MAX_SIGNATURE_BYTES", str(2 * 1024 * 1024))
)
QUOTATION_SOFFICE_BINARY = os.getenv(
    "QUOTATION_SOFFICE_BINARY",
    "soffice",
)
QUOTATION_RENDER_TIMEOUT_SECONDS = float(
    os.getenv("QUOTATION_RENDER_TIMEOUT_SECONDS", "120")
)
QUOTATION_RENDER_CONCURRENCY = max(
    int(os.getenv("QUOTATION_RENDER_CONCURRENCY", "1")),
    1,
)
QUOTATION_RENDER_LOCK_DIR = os.getenv(
    "QUOTATION_RENDER_LOCK_DIR",
    os.path.join(STORAGE_ROOT, ".quotation-render-locks"),
)
QUOTATION_RENDER_RETRY_SECONDS = max(
    int(os.getenv("QUOTATION_RENDER_RETRY_SECONDS", "10")),
    1,
)
QUOTATION_AUDIT_RETENTION_DAYS = int(
    os.getenv("QUOTATION_AUDIT_RETENTION_DAYS", "365")
)
QUOTATION_AUDIT_EXPORT_MAX_ROWS = int(
    os.getenv("QUOTATION_AUDIT_EXPORT_MAX_ROWS", "50000")
)
QUOTATION_STORAGE_ROUTER_ENABLED = (
    os.getenv("QUOTATION_STORAGE_ROUTER_ENABLED", "true").lower() == "true"
)
QUOTATION_DOCUMENT_REPLICA_ENABLED = (
    os.getenv("QUOTATION_DOCUMENT_REPLICA_ENABLED", "true").lower() == "true"
)
QUOTATION_DOCUMENT_RETENTION_DAYS = max(
    int(os.getenv("QUOTATION_DOCUMENT_RETENTION_DAYS", "30")),
    1,
)
QUOTATION_DOCUMENT_PURGE_BATCH_SIZE = max(
    min(int(os.getenv("QUOTATION_DOCUMENT_PURGE_BATCH_SIZE", "100")), 500),
    1,
)
QUOTATION_FEISHU_DIRECT_LINK_MODE = os.getenv(
    "QUOTATION_FEISHU_DIRECT_LINK_MODE",
    "trusted",
)
QUOTATION_FEISHU_PERIODIC_SYNC_ENABLED = (
    os.getenv("QUOTATION_FEISHU_PERIODIC_SYNC_ENABLED", "true").lower()
    == "true"
)
QUOTATION_FEISHU_SYNC_INTERVAL_SECONDS = max(
    int(os.getenv("QUOTATION_FEISHU_SYNC_INTERVAL_SECONDS", "600")),
    60,
)
QUOTATION_FEISHU_LOGIN_SYNC_COOLDOWN_SECONDS = max(
    int(os.getenv("QUOTATION_FEISHU_LOGIN_SYNC_COOLDOWN_SECONDS", "300")),
    0,
)
