# Generated by Codex on 2026-07-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_ops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelSku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canonical_sku_code",
                    models.CharField(db_index=True, max_length=255),
                ),
                ("upstream_model_name", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                (
                    "variant_type",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            ("cloud_hosted", "Cloud Hosted"),
                            ("alias", "Alias"),
                            ("reseller", "Reseller"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=50,
                    ),
                ),
                (
                    "region",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "mode",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "api_type",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("capabilities", models.JSONField(blank=True, default=dict)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                (
                    "routing_status",
                    models.CharField(
                        choices=[
                            ("candidate", "Candidate"),
                            ("confirmed", "Confirmed"),
                            ("locked", "Locked"),
                        ],
                        db_index=True,
                        default="candidate",
                        max_length=30,
                    ),
                ),
                (
                    "is_routable",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skus",
                        to="llm_ops.metamodel",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_skus",
                        to="llm_ops.llmprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["provider__name", "display_name", "id"],
            },
        ),
        migrations.CreateModel(
            name="SourceSkuOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exposed_model_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=255,
                    ),
                ),
                (
                    "pricing_method",
                    models.CharField(
                        choices=[
                            ("collected", "Collected"),
                            ("manual", "Manual"),
                            ("derived_discount", "Derived Discount"),
                        ],
                        default="collected",
                        max_length=50,
                    ),
                ),
                ("discount_rules", models.JSONField(blank=True, default=dict)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sku_offerings",
                        to="llm_ops.llmprovider",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerings",
                        to="llm_ops.modelsku",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sku_offerings",
                        to="llm_ops.pricecollectionsource",
                    ),
                ),
                (
                    "upstream_offering",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_offerings",
                        to="llm_ops.sourceskuoffering",
                    ),
                ),
            ],
            options={
                "ordering": ["source__name", "sku__display_name", "id"],
            },
        ),
        migrations.AddField(
            model_name="llmmodel",
            name="sku",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_models",
                to="llm_ops.modelsku",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="modelpriceitem",
            name="uq_llm_ops_model_price_item_fingerprint",
        ),
        migrations.RemoveConstraint(
            model_name="collectedmodelpricehistory",
            name="uq_llm_ops_price_history_fingerprint",
        ),
        migrations.RemoveConstraint(
            model_name="collectedmodelpricesnapshot",
            name="uq_llm_ops_source_platform_snapshot",
        ),
        migrations.RemoveIndex(
            model_name="modelpriceitem",
            name="llm_ops_mod_model_i_8a6bbb_idx",
        ),
        migrations.AlterModelOptions(
            name="modelpriceitem",
            options={
                "ordering": [
                    "provider__name",
                    "sku__display_name",
                    "dimension",
                    "tier_start",
                    "id",
                ],
            },
        ),
        migrations.AlterField(
            model_name="modelpriceitem",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_items",
                to="llm_ops.llmmodel",
            ),
        ),
        migrations.AddField(
            model_name="modelpriceitem",
            name="base_price_fingerprint",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="modelpriceitem",
            name="derived_from_price_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_price_items",
                to="llm_ops.modelpriceitem",
            ),
        ),
        migrations.AddField(
            model_name="modelpriceitem",
            name="offering",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="price_items",
                to="llm_ops.sourceskuoffering",
            ),
        ),
        migrations.AddField(
            model_name="modelpriceitem",
            name="sku",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="price_items",
                to="llm_ops.modelsku",
            ),
        ),
        migrations.AddField(
            model_name="collectedmodelpricehistory",
            name="offering",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collected_price_history",
                to="llm_ops.sourceskuoffering",
            ),
        ),
        migrations.AddField(
            model_name="collectedmodelpricehistory",
            name="sku",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collected_price_history",
                to="llm_ops.modelsku",
            ),
        ),
        migrations.AddField(
            model_name="collectedmodelpricesnapshot",
            name="offering",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collected_price_snapshots",
                to="llm_ops.sourceskuoffering",
            ),
        ),
        migrations.AddField(
            model_name="collectedmodelpricesnapshot",
            name="sku",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collected_price_snapshots",
                to="llm_ops.modelsku",
            ),
        ),
        migrations.AddIndex(
            model_name="modelpriceitem",
            index=models.Index(
                fields=["sku", "dimension", "is_current"],
                name="llm_ops_mod_sku_id_37e318_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="modelpriceitem",
            index=models.Index(
                fields=["offering", "dimension", "is_current"],
                name="llm_ops_mod_offerin_ffd5f3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelsku",
            constraint=models.UniqueConstraint(
                fields=(
                    "provider",
                    "canonical_sku_code",
                    "region",
                    "mode",
                    "api_type",
                ),
                name="uq_llm_ops_model_sku_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceskuoffering",
            constraint=models.UniqueConstraint(
                fields=("source", "sku", "exposed_model_name"),
                name="uq_llm_ops_source_sku_offering",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelpriceitem",
            constraint=models.UniqueConstraint(
                fields=(
                    "offering",
                    "dimension",
                    "billing_unit",
                    "currency",
                    "price_fingerprint",
                ),
                name="uq_llm_ops_offering_price_item_fingerprint",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectedmodelpricesnapshot",
            constraint=models.UniqueConstraint(
                fields=("source", "offering", "source_platform_id"),
                name="uq_llm_ops_offering_platform_snapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectedmodelpricehistory",
            constraint=models.UniqueConstraint(
                fields=(
                    "source",
                    "offering",
                    "source_platform_id",
                    "price_fingerprint",
                ),
                name="uq_llm_ops_offering_history_fingerprint",
            ),
        ),
    ]
