# Generated by Django 5.1.4 on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_ops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resaleplatform",
            name="environment",
            field=models.CharField(
                choices=[
                    ("production", "Production"),
                    ("staging", "Staging"),
                    ("sandbox", "Sandbox"),
                    ("test", "Test"),
                ],
                default="production",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="resaleplatform",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="resaleplatform",
            name="platform_type",
            field=models.CharField(
                choices=[
                    ("agione", "Agione"),
                    ("cloud_marketplace", "Cloud Marketplace"),
                    ("api_gateway", "API Gateway"),
                    ("reseller", "Reseller"),
                    ("internal", "Internal"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="agione",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="resaleplatform",
            name="region_code",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="resaleplatform",
            name="region_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
