# Generated by Django 4.2.30 on 2026-08-04 08:20

import hashlib
import json
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _decimal_string(value):
    if value is None:
        return ""
    return str(Decimal(str(value)))


def _price_fingerprint(currency, items):
    normalized_items = [
        {
            "dimension": dimension,
            "billing_unit": "per_1m_tokens",
            "tier_type": "flat",
            "tier_start": "",
            "tier_end": "",
            "unit_price": _decimal_string(unit_price),
            "spec": {},
        }
        for dimension, unit_price in items
    ]
    normalized_items.sort(key=lambda item: item["dimension"])
    encoded = json.dumps(
        {
            "currency": currency,
            "items": normalized_items,
        },
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _create_backfilled_revision(
    Revision,
    PriceItem,
    *,
    listing,
    version,
    status,
    currency,
    items,
):
    effective_from = listing.updated_at if status == "approved" else None
    revision = Revision.objects.create(
        listing_id=listing.id,
        version=version,
        status=status,
        currency=currency,
        price_fingerprint=_price_fingerprint(currency, items),
        effective_from=effective_from,
    )
    PriceItem.objects.bulk_create(
        [
            PriceItem(
                revision_id=revision.id,
                dimension=dimension,
                billing_unit="per_1m_tokens",
                tier_type="flat",
                unit_price=unit_price,
                spec={},
            )
            for dimension, unit_price in items
        ]
    )
    return revision


def backfill_flat_price_revisions(apps, schema_editor):
    Listing = apps.get_model("llm_ops", "ResaleListing")
    Revision = apps.get_model(
        "llm_ops",
        "ResaleListingPriceRevision",
    )
    PriceItem = apps.get_model("llm_ops", "ResaleListingPriceItem")

    listings = Listing.objects.select_related("platform", "model").iterator()
    for listing in listings:
        currency = (
            (
                listing.currency
                or listing.platform.currency
                or listing.model.currency
                or "USD"
            )
            .strip()
            .upper()
        )
        items = [
            ("text_input", listing.retail_input_price_per_million),
            ("text_output", listing.retail_output_price_per_million),
        ]
        if listing.retail_cache_input_price_per_million is not None:
            items.append(
                (
                    "cache_input",
                    listing.retail_cache_input_price_per_million,
                )
            )

        current_revision = None
        pending_revision = None
        if listing.workflow_status in {"update_draft", "pending_update"}:
            current_revision = _create_backfilled_revision(
                Revision,
                PriceItem,
                listing=listing,
                version=1,
                status="approved",
                currency=currency,
                items=items,
            )
            pending_status = (
                "draft"
                if listing.workflow_status == "update_draft"
                else "submitted"
            )
            pending_revision = _create_backfilled_revision(
                Revision,
                PriceItem,
                listing=listing,
                version=2,
                status=pending_status,
                currency=currency,
                items=items,
            )
        elif listing.workflow_status in {"draft", "pending_publish"}:
            pending_status = (
                "draft" if listing.workflow_status == "draft" else "submitted"
            )
            pending_revision = _create_backfilled_revision(
                Revision,
                PriceItem,
                listing=listing,
                version=1,
                status=pending_status,
                currency=currency,
                items=items,
            )
        else:
            current_revision = _create_backfilled_revision(
                Revision,
                PriceItem,
                listing=listing,
                version=1,
                status="approved",
                currency=currency,
                items=items,
            )

        Listing.objects.filter(pk=listing.id).update(
            current_price_revision_id=(
                current_revision.id if current_revision else None
            ),
            pending_price_revision_id=(
                pending_revision.id if pending_revision else None
            ),
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("llm_ops", "0008_performance_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResaleListingPriceRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(max_length=10)),
                (
                    "price_fingerprint",
                    models.CharField(db_index=True, max_length=64),
                ),
                (
                    "effective_from",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resale_listing_price_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_revisions",
                        to="llm_ops.resalelisting",
                    ),
                ),
            ],
            options={
                "ordering": ["listing_id", "version"],
            },
        ),
        migrations.CreateModel(
            name="ResaleListingPriceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dimension",
                    models.CharField(
                        choices=[
                            ("text_input", "Text Input"),
                            ("text_output", "Text Output"),
                            ("cache_input", "Cache Input"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "billing_unit",
                    models.CharField(
                        choices=[("per_1m_tokens", "Per 1M Tokens")],
                        default="per_1m_tokens",
                        max_length=50,
                    ),
                ),
                (
                    "tier_type",
                    models.CharField(
                        choices=[
                            ("flat", "Flat"),
                            ("usage_range", "Usage Range"),
                            ("volume", "Volume"),
                        ],
                        default="flat",
                        max_length=50,
                    ),
                ),
                (
                    "tier_start",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "tier_end",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=6, max_digits=14),
                ),
                ("spec", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="llm_ops.resalelistingpricerevision",
                    ),
                ),
            ],
            options={
                "ordering": ["dimension", "tier_start", "id"],
            },
        ),
        migrations.AddField(
            model_name="resalelisting",
            name="current_price_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for_listings",
                to="llm_ops.resalelistingpricerevision",
            ),
        ),
        migrations.AddField(
            model_name="resalelisting",
            name="pending_price_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_for_listings",
                to="llm_ops.resalelistingpricerevision",
            ),
        ),
        migrations.AddConstraint(
            model_name="resalelistingpricerevision",
            constraint=models.UniqueConstraint(
                fields=("listing", "version"),
                name="uq_llm_ops_listing_price_revision_version",
            ),
        ),
        migrations.AddIndex(
            model_name="resalelistingpriceitem",
            index=models.Index(
                fields=["revision", "dimension", "tier_start"],
                name="llmops_resale_item_tier_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="resalelistingpriceitem",
            constraint=models.CheckConstraint(
                check=models.Q(("unit_price__gte", 0)),
                name="ck_llm_ops_resale_item_price_nonnegative",
            ),
        ),
        migrations.RunPython(
            backfill_flat_price_revisions,
            migrations.RunPython.noop,
        ),
    ]
