# Generated by Django 5.1.4 on 2026-08-07 02:33

from django.db import migrations, models

TIER_FLAT = "flat"


def backfill_pricing_format(apps, schema_editor):
    ResaleListing = apps.get_model("llm_ops", "ResaleListing")
    ResaleListingPriceItem = apps.get_model(
        "llm_ops",
        "ResaleListingPriceItem",
    )
    for listing in ResaleListing.objects.iterator():
        revision = (
            listing.pending_price_revision or listing.current_price_revision
        )
        if revision is None:
            continue
        tier_types = set(
            ResaleListingPriceItem.objects.filter(
                revision=revision
            ).values_list("tier_type", flat=True)
        )
        if not tier_types:
            continue
        if tier_types == {TIER_FLAT}:
            pricing_format = "flat"
        elif TIER_FLAT in tier_types:
            pricing_format = "mixed"
        else:
            pricing_format = "usage_range"
        ResaleListing.objects.filter(pk=listing.pk).update(
            pricing_format=pricing_format
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "llm_ops",
            "0009_resalelistingpricerevision_resalelistingpriceitem_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="resalelisting",
            name="pricing_format",
            field=models.CharField(
                choices=[
                    ("flat", "Flat"),
                    ("usage_range", "Usage Range"),
                    ("mixed", "Mixed"),
                ],
                db_index=True,
                default="flat",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            backfill_pricing_format,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
