# Generated by Django 5.1.4 on 2026-08-04 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def bind_existing_online_revisions(apps, schema_editor):
    """Treat the approved revision on an online listing as published."""
    Listing = apps.get_model("llm_ops", "ResaleListing")
    Listing.objects.filter(
        workflow_status="online",
        current_price_revision_id__isnull=False,
        published_price_revision_id__isnull=True,
    ).update(published_price_revision_id=models.F("current_price_revision_id"))


def unbind_existing_online_revisions(apps, schema_editor):
    """Clear publication pointers created by the forward migration."""
    Listing = apps.get_model("llm_ops", "ResaleListing")
    Listing.objects.update(published_price_revision_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("llm_ops", "0010_usagereconciliationrecord_cache_input_tokens"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resalelisting",
            name="published_price_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="llm_ops.resalelistingpricerevision",
            ),
        ),
        migrations.AddField(
            model_name="resalelistingpricerevision",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resalelistingpricerevision",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="llm_ops_approved_resale_price_revisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resalelistingpricerevision",
            name="decision_fingerprint",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="resalelistingpricerevision",
            name="decision_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="resalelistingpricerevision",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resalelistingpricerevision",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="llm_ops_submitted_resale_price_revisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            bind_existing_online_revisions,
            unbind_existing_online_revisions,
        ),
    ]
