# Generated by Django 5.1.4 on 2026-07-13 01:44

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

from data_ops.models import default_feishu_required_permissions


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataOpsGlobalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(default=1, unique=True),
                ),
                (
                    "feishu_app_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("feishu_app_secret", models.TextField(blank=True)),
                (
                    "feishu_date_timezone",
                    models.CharField(default="Asia/Shanghai", max_length=64),
                ),
                (
                    "active_sync_job_timeout_hours",
                    models.PositiveIntegerField(default=3),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Data Ops Global Configuration",
                "verbose_name_plural": "Data Ops Global Configuration",
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_record_id",
                    models.CharField(db_index=True, max_length=255),
                ),
                ("source_app_token", models.CharField(max_length=100)),
                ("source_table_id", models.CharField(max_length=100)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "signing_entity",
                    models.CharField(blank=True, max_length=255),
                ),
                ("channel_type", models.CharField(blank=True, max_length=100)),
                (
                    "enduser_customer",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "order_platform",
                    models.CharField(blank=True, max_length=100),
                ),
                ("sales_person", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("currency", models.CharField(blank=True, max_length=20)),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "product_category",
                    models.CharField(blank=True, max_length=100),
                ),
                ("signing_type", models.CharField(blank=True, max_length=100)),
                ("signing_date", models.DateField(blank=True, null=True)),
                ("service_start", models.DateField(blank=True, null=True)),
                ("service_end", models.DateField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=50)),
                ("filing_type", models.CharField(blank=True, max_length=100)),
                (
                    "contract_sub_type",
                    models.CharField(blank=True, max_length=100),
                ),
                ("expiry_status", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["contract_number"],
                        name="data_ops_co_contrac_6f0368_idx",
                    ),
                    models.Index(
                        fields=["customer_name"],
                        name="data_ops_co_custome_a49ae0_idx",
                    ),
                    models.Index(
                        fields=["sales_person"],
                        name="data_ops_co_sales_p_bc3761_idx",
                    ),
                    models.Index(
                        fields=["service_end"],
                        name="data_ops_co_service_6daab2_idx",
                    ),
                    models.Index(
                        fields=["status"], name="data_ops_co_status_fd95d7_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "source_app_token",
                            "source_table_id",
                            "source_record_id",
                        ),
                        name="uq_data_ops_contract_source",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FeishuBitableCollectionConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_key", models.CharField(max_length=50)),
                ("table_key", models.CharField(max_length=100)),
                ("source_name", models.CharField(blank=True, max_length=255)),
                ("table_name", models.CharField(blank=True, max_length=255)),
                ("app_token", models.CharField(max_length=100)),
                ("table_id", models.CharField(max_length=100)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "sync_frequency",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "required_permissions",
                    models.JSONField(
                        blank=True,
                        default=default_feishu_required_permissions,
                    ),
                ),
                (
                    "expected_min_records",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "last_preflight_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_manual_trigger_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_scheduled_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_key", "table_key"],
                        name="data_ops_fe_source__d3915d_idx",
                    ),
                    models.Index(
                        fields=["is_enabled", "sync_frequency"],
                        name="data_ops_fe_is_enab_c9f909_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_key", "table_key"),
                        name="uq_data_ops_feishu_collection_config",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OverseaProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_record_id",
                    models.CharField(db_index=True, max_length=255),
                ),
                ("source_app_token", models.CharField(max_length=100)),
                ("source_table_id", models.CharField(max_length=100)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("project_name", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(blank=True, max_length=100)),
                ("po_number", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "payment_channel",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "signing_customer",
                    models.CharField(blank=True, max_length=255),
                ),
                ("product_type", models.CharField(blank=True, max_length=100)),
                ("product_spec", models.CharField(blank=True, max_length=255)),
                ("order_date", models.DateField(blank=True, null=True)),
                ("order_year", models.IntegerField(blank=True, null=True)),
                ("order_month", models.IntegerField(blank=True, null=True)),
                (
                    "purchase_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("purchase_cycle", models.IntegerField(blank=True, null=True)),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=20)),
                (
                    "stat_amount_usd",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("allocation_date", models.DateField(blank=True, null=True)),
                (
                    "allocation_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "license_order_no",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "huawei_cloud_expiry",
                    models.DateField(blank=True, null=True),
                ),
                ("license_expiry", models.DateField(blank=True, null=True)),
                ("timezone", models.CharField(blank=True, max_length=50)),
                (
                    "license_reg_code",
                    models.CharField(blank=True, max_length=255),
                ),
                ("kg_username", models.CharField(blank=True, max_length=100)),
                ("kg_full_name", models.CharField(blank=True, max_length=255)),
                ("end_customer", models.CharField(blank=True, max_length=255)),
                ("kg_email", models.CharField(blank=True, max_length=255)),
                ("cc_email", models.CharField(blank=True, max_length=500)),
                (
                    "project_owner",
                    models.CharField(blank=True, max_length=100),
                ),
                ("invoice_no", models.CharField(blank=True, max_length=100)),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "payment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "payment_currency",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "payment_recipient",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "customer_type",
                    models.CharField(blank=True, max_length=100),
                ),
                ("cost_for", models.CharField(blank=True, max_length=255)),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(blank=True, max_length=100),
                ),
                ("tax_status", models.CharField(blank=True, max_length=100)),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("order_type", models.CharField(blank=True, max_length=100)),
                (
                    "acceptance_status",
                    models.CharField(blank=True, max_length=100),
                ),
                ("order_status", models.CharField(blank=True, max_length=100)),
                (
                    "order_category",
                    models.CharField(blank=True, max_length=100),
                ),
                ("customer_id", models.CharField(blank=True, max_length=100)),
                ("payment_id", models.CharField(blank=True, max_length=100)),
                (
                    "project_sub_no",
                    models.CharField(blank=True, max_length=100),
                ),
                ("remarks", models.CharField(blank=True, max_length=1000)),
                ("tax_voucher", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["country"],
                        name="data_ops_ov_country_855cfd_idx",
                    ),
                    models.Index(
                        fields=["project_owner"],
                        name="data_ops_ov_project_a0d121_idx",
                    ),
                    models.Index(
                        fields=["status"], name="data_ops_ov_status_e149e6_idx"
                    ),
                    models.Index(
                        fields=["license_expiry"],
                        name="data_ops_ov_license_aef3d4_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "source_app_token",
                            "source_table_id",
                            "source_record_id",
                        ),
                        name="uq_data_ops_oversea_project_source",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OverseaSettlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_record_id",
                    models.CharField(db_index=True, max_length=255),
                ),
                ("source_app_token", models.CharField(max_length=100)),
                ("source_table_id", models.CharField(max_length=100)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "project_name_en",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "project_name_cn",
                    models.CharField(blank=True, max_length=255),
                ),
                ("region", models.CharField(blank=True, max_length=100)),
                (
                    "project_category",
                    models.CharField(blank=True, max_length=100),
                ),
                ("project_code", models.CharField(blank=True, max_length=100)),
                (
                    "project_progress",
                    models.CharField(blank=True, max_length=255),
                ),
                ("todo_notes", models.CharField(blank=True, max_length=2000)),
                (
                    "project_overview",
                    models.CharField(blank=True, max_length=2000),
                ),
                (
                    "final_customer",
                    models.CharField(blank=True, max_length=255),
                ),
                ("integrator", models.CharField(blank=True, max_length=255)),
                (
                    "huawei_settlement_party",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "selling_products",
                    models.CharField(blank=True, max_length=1000),
                ),
                (
                    "actual_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "overseas_initial_quote",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "initial_quote_unit",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "estimated_exchange_rate",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=18, null=True
                    ),
                ),
                (
                    "estimated_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "estimated_revenue_unit",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "revenue_diff",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "revenue_diff_unit",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "revenue_diff_reason",
                    models.CharField(blank=True, max_length=500),
                ),
                (
                    "receivable_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "received_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=20)),
                (
                    "aisun_sub_fee_estimate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "huawei_order_time",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "huawei_est_payment_time",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "transit_merchant_est_payment_time",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "master_overseas_link",
                    models.CharField(blank=True, max_length=1000),
                ),
                (
                    "aisun_sub_fee_link",
                    models.CharField(blank=True, max_length=1000),
                ),
                (
                    "authorization_status_link",
                    models.CharField(blank=True, max_length=1000),
                ),
                (
                    "has_initial_quote_attachment",
                    models.BooleanField(default=False),
                ),
                (
                    "has_contract_attachment",
                    models.BooleanField(default=False),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project_code"],
                        name="data_ops_ov_project_0daa13_idx",
                    ),
                    models.Index(
                        fields=["region"], name="data_ops_ov_region_d914e0_idx"
                    ),
                    models.Index(
                        fields=["payment_date"],
                        name="data_ops_ov_payment_68ee8e_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "source_app_token",
                            "source_table_id",
                            "source_record_id",
                        ),
                        name="uq_data_ops_settlement_source",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OwnerAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("canonical", models.CharField(max_length=100)),
                ("alias", models.CharField(max_length=100)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["alias"], name="data_ops_ow_alias_082056_idx"
                    ),
                    models.Index(
                        fields=["canonical"],
                        name="data_ops_ow_canonic_745087_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("canonical", "alias"),
                        name="uq_data_ops_owner_alias_canonical",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_record_id",
                    models.CharField(db_index=True, max_length=255),
                ),
                ("source_app_token", models.CharField(max_length=100)),
                ("source_table_id", models.CharField(max_length=100)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "project_scope",
                    models.CharField(
                        choices=[
                            ("domestic", "Domestic"),
                            ("overseas", "Overseas"),
                        ],
                        max_length=20,
                    ),
                ),
                ("project_code", models.CharField(blank=True, max_length=100)),
                ("domestic_type", models.CharField(blank=True, max_length=50)),
                (
                    "customer_full_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "oa_initiation_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "estimated_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "sales_products",
                    models.CharField(blank=True, max_length=500),
                ),
                (
                    "signing_party_type",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "project_description",
                    models.CharField(blank=True, max_length=1000),
                ),
                (
                    "contract_link",
                    models.CharField(blank=True, max_length=500),
                ),
                ("country", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(blank=True, max_length=100)),
                ("po_number", models.CharField(blank=True, max_length=100)),
                (
                    "payment_channel",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "signing_customer",
                    models.CharField(blank=True, max_length=255),
                ),
                ("end_customer", models.CharField(blank=True, max_length=255)),
                (
                    "customer_type",
                    models.CharField(blank=True, max_length=100),
                ),
                ("product_type", models.CharField(blank=True, max_length=100)),
                ("product_spec", models.CharField(blank=True, max_length=255)),
                ("order_type", models.CharField(blank=True, max_length=100)),
                ("order_status", models.CharField(blank=True, max_length=100)),
                (
                    "acceptance_status",
                    models.CharField(blank=True, max_length=100),
                ),
                ("order_date", models.DateField(blank=True, null=True)),
                ("order_year", models.IntegerField(blank=True, null=True)),
                ("order_month", models.IntegerField(blank=True, null=True)),
                (
                    "order_category",
                    models.CharField(blank=True, max_length=100),
                ),
                ("customer_id", models.CharField(blank=True, max_length=100)),
                ("payment_id", models.CharField(blank=True, max_length=100)),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "stat_amount_usd",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("allocation_date", models.DateField(blank=True, null=True)),
                (
                    "allocation_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "license_order_no",
                    models.CharField(blank=True, max_length=100),
                ),
                ("license_expiry", models.DateField(blank=True, null=True)),
                (
                    "huawei_cloud_expiry",
                    models.DateField(blank=True, null=True),
                ),
                ("timezone", models.CharField(blank=True, max_length=50)),
                (
                    "license_reg_code",
                    models.CharField(blank=True, max_length=255),
                ),
                ("kg_username", models.CharField(blank=True, max_length=100)),
                ("kg_full_name", models.CharField(blank=True, max_length=255)),
                ("kg_email", models.CharField(blank=True, max_length=255)),
                ("cc_email", models.CharField(blank=True, max_length=500)),
                ("invoice_no", models.CharField(blank=True, max_length=100)),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "payment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "payment_currency",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "payment_recipient",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "payment_terms",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "received_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("cost_for", models.CharField(blank=True, max_length=255)),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("tax_status", models.CharField(blank=True, max_length=100)),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("tax_voucher", models.CharField(blank=True, max_length=255)),
                (
                    "project_sub_no",
                    models.CharField(blank=True, max_length=100),
                ),
                ("remarks", models.CharField(blank=True, max_length=1000)),
                ("project_name", models.CharField(blank=True, max_length=255)),
                ("sales_person", models.CharField(blank=True, max_length=100)),
                (
                    "project_owner",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "enduser_customer",
                    models.CharField(blank=True, max_length=255),
                ),
                ("currency", models.CharField(blank=True, max_length=20)),
                ("is_high_potential", models.BooleanField(default=False)),
                ("is_landed", models.BooleanField(default=False)),
                (
                    "license_days_left",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "license_risk_level",
                    models.CharField(blank=True, max_length=20),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project_scope"],
                        name="data_ops_pr_project_1c1533_idx",
                    ),
                    models.Index(
                        fields=["domestic_type"],
                        name="data_ops_pr_domesti_f8c20a_idx",
                    ),
                    models.Index(
                        fields=["country"],
                        name="data_ops_pr_country_f4334c_idx",
                    ),
                    models.Index(
                        fields=["sales_person"],
                        name="data_ops_pr_sales_p_f16291_idx",
                    ),
                    models.Index(
                        fields=["project_owner"],
                        name="data_ops_pr_project_c9c07b_idx",
                    ),
                    models.Index(
                        fields=["status"], name="data_ops_pr_status_0873f3_idx"
                    ),
                    models.Index(
                        fields=["license_expiry"],
                        name="data_ops_pr_license_39524d_idx",
                    ),
                    models.Index(
                        fields=["project_scope", "sales_person"],
                        name="data_ops_pr_project_7fa2df_idx",
                    ),
                    models.Index(
                        fields=["project_scope", "country"],
                        name="data_ops_pr_project_978427_idx",
                    ),
                    models.Index(
                        fields=["project_scope", "status"],
                        name="data_ops_pr_project_42a28f_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "source_app_token",
                            "source_table_id",
                            "source_record_id",
                        ),
                        name="uq_data_ops_project_source",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectInit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_record_id",
                    models.CharField(db_index=True, max_length=255),
                ),
                ("source_app_token", models.CharField(max_length=100)),
                ("source_table_id", models.CharField(max_length=100)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("project_code", models.CharField(blank=True, max_length=100)),
                (
                    "domestic_international",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "customer_full_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "oa_initiation_date",
                    models.DateField(blank=True, null=True),
                ),
                ("project_name", models.CharField(blank=True, max_length=255)),
                (
                    "project_description",
                    models.CharField(blank=True, max_length=1000),
                ),
                ("sales_person", models.CharField(blank=True, max_length=100)),
                (
                    "sales_products",
                    models.CharField(blank=True, max_length=500),
                ),
                (
                    "estimated_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=20)),
                (
                    "signing_party_type",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "enduser_customer",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "contract_link",
                    models.CharField(blank=True, max_length=500),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project_code"],
                        name="data_ops_pr_project_21df9e_idx",
                    ),
                    models.Index(
                        fields=["domestic_international"],
                        name="data_ops_pr_domesti_2280e3_idx",
                    ),
                    models.Index(
                        fields=["sales_person"],
                        name="data_ops_pr_sales_p_0af1fc_idx",
                    ),
                    models.Index(
                        fields=["oa_initiation_date"],
                        name="data_ops_pr_oa_init_34e828_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "source_app_token",
                            "source_table_id",
                            "source_record_id",
                        ),
                        name="uq_data_ops_project_init_source",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SalesRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_record_id",
                    models.CharField(db_index=True, max_length=255),
                ),
                ("source_app_token", models.CharField(max_length=100)),
                ("source_table_id", models.CharField(max_length=100)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("project_name", models.CharField(blank=True, max_length=255)),
                ("po_number", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("product_type", models.CharField(blank=True, max_length=100)),
                (
                    "total_amount_usd",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("allocation_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("order_type", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(blank=True, max_length=50)),
                ("sales_person", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project_name"],
                        name="data_ops_sa_project_866f52_idx",
                    ),
                    models.Index(
                        fields=["sales_person"],
                        name="data_ops_sa_sales_p_4ab03e_idx",
                    ),
                    models.Index(
                        fields=["expiry_date"],
                        name="data_ops_sa_expiry__76f03d_idx",
                    ),
                    models.Index(
                        fields=["status"], name="data_ops_sa_status_309622_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "source_app_token",
                            "source_table_id",
                            "source_record_id",
                        ),
                        name="uq_data_ops_sales_record_source",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SyncCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_token", models.CharField(max_length=100)),
                ("table_id", models.CharField(max_length=100)),
                ("source_key", models.CharField(blank=True, max_length=50)),
                ("table_key", models.CharField(blank=True, max_length=100)),
                ("table_name", models.CharField(blank=True, max_length=255)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_success_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("record_count", models.IntegerField(default=0)),
                (
                    "source_revision",
                    models.CharField(blank=True, max_length=64),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("app_token", "table_id"),
                        name="uq_data_ops_sync_cursor",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SyncJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_key", models.CharField(blank=True, max_length=50)),
                ("table_key", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("warning", "Warning"),
                            ("failed", "Failed"),
                            ("running", "Running"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("records_synced", models.IntegerField(default=0)),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=2000),
                ),
                ("locked_by", models.CharField(blank=True, max_length=100)),
                (
                    "lock_acquired_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("results", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "started_at"],
                        name="data_ops_sy_status_6dd86d_idx",
                    ),
                    models.Index(
                        fields=["source_key", "started_at"],
                        name="data_ops_sy_source__6b93c4_idx",
                    ),
                    models.Index(
                        fields=["source_key", "table_key", "started_at"],
                        name="data_ops_sy_source__6ded4c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SyncTableStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_key", models.CharField(max_length=50)),
                ("table_key", models.CharField(max_length=100)),
                ("app_token", models.CharField(max_length=100)),
                ("table_id", models.CharField(max_length=100)),
                ("table_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("warning", "Warning"),
                            ("failed", "Failed"),
                            ("running", "Running"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "issue_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("config_missing", "Configuration missing"),
                            ("token_error", "Token error"),
                            ("app_access_denied", "App access denied"),
                            ("table_access_denied", "Table access denied"),
                            ("field_access_denied", "Field access denied"),
                            ("field_missing", "Field missing"),
                            ("pagination_incomplete", "Pagination incomplete"),
                            ("zero_records_unexpected", "Unexpected zero"),
                            ("network_error", "Network error"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=1000)),
                (
                    "resolution_hint",
                    models.CharField(blank=True, max_length=1000),
                ),
                (
                    "expected_fields",
                    models.JSONField(blank=True, default=list),
                ),
                ("missing_fields", models.JSONField(blank=True, default=list)),
                (
                    "expected_min_records",
                    models.IntegerField(blank=True, null=True),
                ),
                ("expected_record_floor", models.IntegerField(default=0)),
                ("record_count", models.IntegerField(default=0)),
                (
                    "last_checked_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status"], name="data_ops_sy_status_8530b4_idx"
                    ),
                    models.Index(
                        fields=["issue_code"],
                        name="data_ops_sy_issue_c_f8b286_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_key", "table_key"),
                        name="uq_data_ops_sync_table_status",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContractHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_record_id",
                    models.CharField(db_index=True, max_length=100),
                ),
                ("field_name", models.CharField(max_length=255)),
                ("old_value", models.CharField(blank=True, max_length=5000)),
                ("new_value", models.CharField(blank=True, max_length=5000)),
                (
                    "changed_by",
                    models.CharField(
                        blank=True, db_index=True, max_length=255
                    ),
                ),
                ("changed_at", models.DateTimeField(db_index=True)),
                (
                    "change_type",
                    models.CharField(default="update", max_length=20),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_entries",
                        to="data_ops.contract",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["contract", "changed_at"],
                        name="data_ops_co_contrac_601f18_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "contract",
                            "source_record_id",
                            "field_name",
                            "changed_at",
                        ),
                        name="uq_data_ops_history_dedup",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DomesticLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_record_id",
                    models.CharField(db_index=True, max_length=255),
                ),
                ("source_app_token", models.CharField(max_length=100)),
                ("source_table_id", models.CharField(max_length=100)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("ledger_type", models.CharField(blank=True, max_length=20)),
                ("currency", models.CharField(blank=True, max_length=20)),
                ("signing_date", models.DateField(blank=True, null=True)),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=255),
                ),
                ("project_name", models.CharField(blank=True, max_length=255)),
                ("order_number", models.CharField(blank=True, max_length=100)),
                ("sales_person", models.CharField(blank=True, max_length=100)),
                (
                    "signing_entity",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "total_contract_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "single_receive_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "invoice_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "payment_received",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "outstanding",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("receipt_time", models.DateField(blank=True, null=True)),
                (
                    "expected_payment_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "license_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "license_unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "payment_progress",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "payment_status",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "payment_situation",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "payment_terms",
                    models.CharField(blank=True, max_length=100),
                ),
                ("sales_mode", models.CharField(blank=True, max_length=50)),
                (
                    "purchase_product",
                    models.CharField(blank=True, max_length=100),
                ),
                ("tax_rate", models.CharField(blank=True, max_length=20)),
                ("year", models.CharField(blank=True, max_length=10)),
                ("project_code", models.CharField(blank=True, max_length=100)),
                ("remarks", models.CharField(blank=True, max_length=1000)),
                ("payment_item", models.CharField(blank=True, max_length=255)),
                (
                    "payment_party",
                    models.CharField(blank=True, max_length=255),
                ),
                ("payee_name", models.CharField(blank=True, max_length=255)),
                (
                    "payment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("signing_mode", models.CharField(blank=True, max_length=100)),
                (
                    "counterparty_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="data_ops.contract",
                    ),
                ),
                (
                    "linked_ledger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_payments",
                        to="data_ops.domesticledger",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ledger_type", "payment_status"],
                        name="data_ops_do_ledger__40f424_idx",
                    ),
                    models.Index(
                        fields=["sales_person"],
                        name="data_ops_do_sales_p_b0db7b_idx",
                    ),
                    models.Index(
                        fields=["signing_entity"],
                        name="data_ops_do_signing_451b05_idx",
                    ),
                    models.Index(
                        fields=["expected_payment_date"],
                        name="data_ops_do_expecte_64ab09_idx",
                    ),
                    models.Index(
                        fields=["year"], name="data_ops_do_year_42289f_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "source_app_token",
                            "source_table_id",
                            "source_record_id",
                        ),
                        name="uq_data_ops_ledger_source",
                    )
                ],
            },
        ),
    ]
