# Generated by Django 5.1.4 on 2026-07-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ops', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwnerAlias',
        ),
        migrations.AddField(
            model_name='contract',
            name='owner_identities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='domesticledger',
            name='owner_identities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='overseaproject',
            name='owner_identities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='overseasettlement',
            name='owner_identities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='owner_identities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='projectinit',
            name='owner_identities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='owner_identities',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
