# Generated by Django 5.1.4 on 2026-05-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('path_prefix', models.CharField(help_text='以 / 开头和结尾，如 /log/ 或 /analytics/', max_length=100, unique=True, verbose_name='路径前缀')),
                ('target_host', models.CharField(help_text='如 192.168.1.100:8080', max_length=200, verbose_name='目标服务地址')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('auth_type', models.CharField(choices=[('none', '无认证'), ('token_fetch', '外部服务自签发 Token'), ('static_token', '静态 Token'), ('hmac', 'HMAC 签名')], default='none', max_length=20, verbose_name='认证方式')),
                ('static_token', models.CharField(blank=True, default='', help_text='静态 Token，auth_type 为 static_token 时使用', max_length=500, verbose_name='静态 Token')),
                ('token_fetch_url', models.CharField(blank=True, default='', help_text='从外部服务获取 Token 的接口，如 http://1.2.3.4:8080/auth/token', max_length=500, verbose_name='Token 获取 URL')),
                ('token_fetch_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='POST', max_length=10, verbose_name='Token 获取方法')),
                ('token_fetch_headers', models.JSONField(blank=True, default=dict, help_text='获取 Token 时的额外请求头，如 {"X-API-Key": "xxx"}', verbose_name='Token 获取请求头')),
                ('token_fetch_body', models.JSONField(blank=True, default=dict, help_text='获取 Token 时的请求体 JSON', verbose_name='Token 获取请求体')),
                ('cached_token', models.TextField(blank=True, default='', editable=False, verbose_name='缓存的 Token')),
                ('cached_token_expires_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Token 过期时间')),
                ('hmac_secret', models.CharField(blank=True, default='', help_text='与外部服务共享的 HMAC 密钥', max_length=500, verbose_name='HMAC 密钥')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '外部站点',
                'verbose_name_plural': '外部站点',
                'db_table': 'external_proxy_site',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['path_prefix'], name='external_pr_path_pr_f26f02_idx'), models.Index(fields=['is_active'], name='external_pr_is_acti_764d91_idx')],
            },
        ),
    ]
