# Generated by Django 5.1.4 on 2026-05-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_proxy', '0001_add_external_site'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='externalsite',
            name='external_pr_path_pr_f26f02_idx',
        ),
        migrations.RemoveField(
            model_name='externalsite',
            name='path_prefix',
        ),
        migrations.AddField(
            model_name='externalsite',
            name='slug',
            field=models.SlugField(blank=True, help_text='仅填写标识，如 romo_log，实际访问路径为 /proxy/<slug>/', max_length=100, null=True, unique=True, verbose_name='代理标识'),
        ),
        migrations.AddIndex(
            model_name='externalsite',
            index=models.Index(fields=['slug'], name='external_pr_slug_ebd0af_idx'),
        ),
    ]
