# Generated by Django 5.1.4 on 2026-05-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_proxy', '0002_remove_externalsite_external_pr_path_pr_f26f02_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsite',
            name='access_mode',
            field=models.CharField(choices=[('proxy', '平台代理'), ('iframe', 'Iframe 嵌入'), ('redirect', '直接跳转')], default='proxy', max_length=20, verbose_name='访问方式'),
        ),
        migrations.AddField(
            model_name='externalsite',
            name='external_url',
            field=models.CharField(blank=True, default='', help_text='iframe/跳转模式下填写浏览器可访问地址，如 https://myteamone.io', max_length=500, verbose_name='外部 URL'),
        ),
        migrations.AddField(
            model_name='externalsite',
            name='required_feature',
            field=models.CharField(blank=True, default='admin_console', help_text='为空时默认使用 admin_console', max_length=100, verbose_name='所需功能标识'),
        ),
        migrations.AlterField(
            model_name='externalsite',
            name='target_host',
            field=models.CharField(help_text='代理模式下填写 host:port，如 frontend:3000 或 127.0.0.1:18082', max_length=200, verbose_name='目标服务地址'),
        ),
    ]
