# Generated by Django 5.1.4 on 2026-02-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_billing", "0005_merge_hourly_cost_and_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingdata",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Cumulative total cost for the period",
                max_digits=20,
            ),
        ),
        migrations.AlterField(
            model_name="cloudprovider",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("aws", "AWS"),
                    ("huawei", "Huawei Cloud (China)"),
                    ("huawei-intl", "Huawei Cloud (International)"),
                    ("alibaba", "Alibaba Cloud"),
                    ("azure", "Azure"),
                ],
                help_text="Cloud provider type",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="billingdata",
            index=models.Index(
                fields=["provider", "account_id", "period", "hour"],
                name="cloud_billi_provide_28fa94_idx",
            ),
        ),
    ]
