# Generated by Django 5.1.4 on 2026-05-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_billing', '0014_recharge_approval_records'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rechargeapprovalevent',
            new_name='cloud_billi_record__8f2e4e_idx',
            old_name='cloud_billi_record__8708f8_idx',
        ),
        migrations.RenameIndex(
            model_name='rechargeapprovalevent',
            new_name='cloud_billi_trace_i_cd0a14_idx',
            old_name='cloud_billi_trace_i_d4ca9f_idx',
        ),
        migrations.RenameIndex(
            model_name='rechargeapprovalevent',
            new_name='cloud_billi_event_t_94fcb6_idx',
            old_name='cloud_billi_event_t_4b27c4_idx',
        ),
        migrations.RenameIndex(
            model_name='rechargeapprovalllmrun',
            new_name='cloud_billi_record__db0daa_idx',
            old_name='cloud_billi_record__8d41a1_idx',
        ),
        migrations.RenameIndex(
            model_name='rechargeapprovalllmrun',
            new_name='cloud_billi_trace_i_4eb43c_idx',
            old_name='cloud_billi_trace_i_26fd11_idx',
        ),
        migrations.RenameIndex(
            model_name='rechargeapprovalllmrun',
            new_name='cloud_billi_stage_7c527f_idx',
            old_name='cloud_billi_stage_efced4_idx',
        ),
        migrations.RenameIndex(
            model_name='rechargeapprovalrecord',
            new_name='cloud_billi_provide_b147f4_idx',
            old_name='cloud_billi_provide_e0e6a9_idx',
        ),
        migrations.RenameIndex(
            model_name='rechargeapprovalrecord',
            new_name='cloud_billi_status_d9722e_idx',
            old_name='cloud_billi_status_25a8ae_idx',
        ),
        migrations.RenameIndex(
            model_name='rechargeapprovalrecord',
            new_name='cloud_billi_trace_i_8ad8ac_idx',
            old_name='cloud_billi_trace_i_7940d6_idx',
        ),
        migrations.AlterField(
            model_name='alertrecord',
            name='increase_percent',
            field=models.DecimalField(decimal_places=2, help_text='Cost increase percentage', max_digits=10),
        ),
        migrations.AlterField(
            model_name='rechargeapprovalllmrun',
            name='runner_type',
            field=models.CharField(choices=[('agent', 'Agent'), ('llm', 'LLM'), ('script', 'Script'), ('skill_http', 'Skill HTTP')], default='agent', max_length=20),
        ),
    ]
