# Generated by Django 5.1.4 on 2026-05-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_billing', '0015_increase_percent_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrecord',
            name='resource_cost_details',
            field=models.JSONField(blank=True, default=list, help_text='Resource-level cost breakdown at alert time, format: [{name, cost, owner?}, ...]'),
        ),
    ]
