# Generated by Django 5.1.4 on 2026-05-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_billing', '0016_add_resource_cost_details_to_alert_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrecord',
            name='cost_period',
            field=models.CharField(blank=True, default='today', help_text="Data source period: 'today' for daily API data, 'month' for stored monthly data", max_length=10),
        ),
    ]
