# Generated by Django 5.1.4 on 2026-09-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_billing', '0024_billing_collection_health'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='billingdata',
            index=models.Index(
                fields=['provider', 'account_id', '-day', '-collected_at'],
                name='cbill_latest_billing_idx',
            ),
        ),
    ]
