# Generated by Django 5.1.4 on 2026-03-02 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_collector", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="rawdatarecord",
            new_name="data_collec_user_id_6e8e28_idx",
            old_name="data_collect_user_id_platform_idx",
        ),
        migrations.RenameIndex(
            model_name="rawdatarecord",
            new_name="data_collec_platfor_78285a_idx",
            old_name="data_collect_platform_is_del_idx",
        ),
    ]
