# Generated by Django 5.1.4 on 2026-02-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifier", "0004_refactor_to_metadata_json"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notificationrecord",
            new_name="notifier_no_status_4cb7c9_idx",
            old_name="notifier_no_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationrecord",
            new_name="notifier_no_source__71d6fa_idx",
            old_name="notifier_no_source_app_type_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationrecord",
            new_name="notifier_no_provide_92dff5_idx",
            old_name="notifier_no_provider_status_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationrecord",
            new_name="notifier_no_user_id_254858_idx",
            old_name="notifier_no_user_created_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationrecord",
            new_name="notifier_no_created_0d1d41_idx",
            old_name="notifier_no_created_at_idx",
        ),
        migrations.AlterField(
            model_name="notificationrecord",
            name="source_type",
            field=models.CharField(
                blank=True,
                help_text="Source type (e.g., 'alert', 'task', 'event')",
                max_length=100,
            ),
        ),
    ]
