# Generated by Django 5.1.4 on 2026-03-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_collector", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawdataattachment",
            name="file_url",
            field=models.CharField(
                help_text="HTTP path for download (/media/storage/data_collector/...)",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="rawdatarecord",
            name="source_unique_id",
            field=models.CharField(
                db_index=True,
                help_text="Platform-side unique id (e.g. issue key)",
                max_length=255,
            ),
        ),
    ]
