# Generated by Django 5.1.4 on 2026-04-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyperbdr_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='host',
            name='tenant',
        ),
        migrations.RemoveConstraint(
            model_name='license',
            name='hyperbdr_dashboard_license_source_tenant_scene_unique',
        ),
        migrations.RemoveConstraint(
            model_name='tenant',
            name='hyperbdr_dashboard_tenant_source_unique',
        ),
        migrations.RenameIndex(
            model_name='license',
            new_name='hbdr_dash_license_scene_idx',
            old_name='hbdr_moni_data_so_d12949_idx',
        ),
        migrations.RenameIndex(
            model_name='license',
            new_name='hbdr_dash_lic_ten_scene_idx',
            old_name='hbdr_moni_tenant_8a5776_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='hbdr_dash_tenant_status_idx',
            old_name='hbdr_moni_data_so_bb4939_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='hbdr_dash_tenant_name_idx',
            old_name='hbdr_moni_data_so_24a173_idx',
        ),
        migrations.RemoveField(
            model_name='collectiontask',
            name='total_hosts',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='collect_interval',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='last_collected_at',
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.UniqueConstraint(fields=('data_source', 'tenant', 'scene'), name='hyperbdr_dash_lic_src_ten_uniq'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(fields=('data_source', 'source_tenant_id'), name='hyperbdr_dash_tenant_src_uniq'),
        ),
        migrations.DeleteModel(
            name='Host',
        ),
    ]
