# Generated by Django 5.1.4 on 2026-10-09 02:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("mcp_server", "0001_initial"),
        ("mcp_server", "0002_unique_issuer_user"),
        ("mcp_server", "0003_mcp_external_account"),
        ("mcp_server", "0004_mcp_identity_provider"),
        (
            "mcp_server",
            "0005_mcpoauthauthorization_mcpoauthauthorizationcode_and_more",
        ),
        ("mcp_server", "0006_oauth_client_secret"),
        ("mcp_server", "0007_bind_tokens_to_issuer"),
        ("mcp_server", "0008_mcprobotcredential"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("invoice", "0001_initial_squashed_0015_invoice_revision"),
        ("quotation", "0037_imported_quote_dates_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="McpOAuthAuthorization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_id", models.CharField(max_length=255)),
                ("redirect_uri", models.TextField()),
                ("state", models.TextField(blank=True)),
                ("code_challenge", models.CharField(max_length=128)),
                ("scopes", models.JSONField(default=list)),
                ("resource", models.TextField()),
                ("issuer", models.TextField(default="")),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="McpOAuthClient",
            fields=[
                (
                    "client_id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                (
                    "client_secret_encrypted",
                    models.TextField(blank=True, default=""),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="McpOAuthAuthorizationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(max_length=64, unique=True)),
                ("client_id", models.CharField(max_length=255)),
                ("redirect_uri", models.TextField()),
                (
                    "redirect_uri_provided_explicitly",
                    models.BooleanField(default=True),
                ),
                ("code_challenge", models.CharField(max_length=128)),
                ("scopes", models.JSONField(default=list)),
                ("resource", models.TextField()),
                ("issuer", models.TextField(default="")),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="McpOAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "family_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4),
                ),
                (
                    "token_type",
                    models.CharField(
                        choices=[("access", "Access"), ("refresh", "Refresh")],
                        max_length=8,
                    ),
                ),
                ("client_id", models.CharField(max_length=255)),
                ("scopes", models.JSONField(default=list)),
                ("resource", models.TextField()),
                ("issuer", models.TextField(default="")),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="McpRobotCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("scopes", models.JSONField(default=list)),
                ("resource", models.TextField()),
                ("issuer", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_mcp_robot_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mcp_robot_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mcp_robot_credentials",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="McpDocumentPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_hash", models.CharField(max_length=64)),
                ("page_number", models.PositiveIntegerField(default=0)),
                ("text", models.TextField()),
                (
                    "invoice_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_pages",
                        to="invoice.invoicedocument",
                    ),
                ),
                (
                    "quotation_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_pages",
                        to="quotation.documentasset",
                    ),
                ),
            ],
            options={
                "db_table": "mcp_document_pages",
                "indexes": [
                    models.Index(
                        fields=["quotation_asset", "content_hash"],
                        name="mcp_page_quote_hash",
                    ),
                    models.Index(
                        fields=["invoice_document", "content_hash"],
                        name="mcp_page_invoice_hash",
                    ),
                ],
            },
        ),
    ]
