# Generated by Django 5.1.4 on 2026-02-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_tracker", "0002_remove_task_execution"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="llmusage",
            new_name="llm_tracker_user_id_5800dd_idx",
            old_name="llm_track_user_created_idx",
        ),
        migrations.RenameIndex(
            model_name="llmusage",
            new_name="llm_tracker_model_534b34_idx",
            old_name="llm_track_model_created_idx",
        ),
        migrations.RenameIndex(
            model_name="llmusage",
            new_name="llm_tracker_total_t_f8ac69_idx",
            old_name="llm_track_tokens_created_idx",
        ),
        migrations.RenameIndex(
            model_name="llmusage",
            new_name="llm_tracker_success_3cd796_idx",
            old_name="llm_track_success_created_idx",
        ),
        migrations.RenameIndex(
            model_name="llmusage",
            new_name="llm_tracker_created_60798a_idx",
            old_name="llm_track_created_at_idx",
        ),
        migrations.AlterField(
            model_name="llmusage",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Context and source info: node_name, source_type, "
                    "source_task_id, source_path, etc. Flat structure for "
                    "flexible querying."
                ),
            ),
        ),
    ]
