# Generated by Django 5.1.15 on 2026-07-09 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import quotation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAsset",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=quotation.models._uuid,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("excel", "excel"),
                            ("pdf", "pdf"),
                            ("signature", "signature"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=120)),
                ("storage_key", models.CharField(max_length=512)),
                ("size_bytes", models.IntegerField(default=0)),
                ("source", models.CharField(default="local", max_length=20)),
                (
                    "feishu_file_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_by_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "document_assets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=quotation.models._uuid,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quote_no",
                    models.CharField(
                        db_index=True, max_length=120, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("generated", "generated"),
                            ("cancelled", "cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("version_current", models.IntegerField(default=1)),
                (
                    "product_line",
                    models.CharField(default="BDR", max_length=40),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "payment_term_option",
                    models.CharField(default="CIA", max_length=40),
                ),
                (
                    "payment_terms",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("quote_date", models.DateField()),
                ("expire_date", models.DateField()),
                ("tax_label", models.CharField(default="VAT", max_length=40)),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18
                    ),
                ),
                (
                    "software_subtotal",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18
                    ),
                ),
                (
                    "others_subtotal",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18
                    ),
                ),
                (
                    "subtotal_before_vat",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18
                    ),
                ),
                (
                    "remarks_disclaimer",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "issuer_company_name",
                    models.CharField(
                        default="OnePro Cloud Limited", max_length=255
                    ),
                ),
                ("issuer_contact_name", models.CharField(max_length=120)),
                ("issuer_contact_email", models.CharField(max_length=255)),
                (
                    "issuer_contact_title",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("issuer_signature", models.TextField(blank=True, default="")),
                ("client_company", models.CharField(max_length=255)),
                ("contact_person", models.CharField(max_length=120)),
                ("email", models.CharField(max_length=255)),
                (
                    "billing_company",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "billing_contact",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "billing_email",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "created_by_email",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "quotations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateAsset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=quotation.models._uuid,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        db_index=True, default="quotation_excel", max_length=40
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "mime_type",
                    models.CharField(
                        default="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        max_length=120,
                    ),
                ),
                ("storage_key", models.CharField(max_length=512)),
                ("size_bytes", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "uploaded_by_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "template_assets",
            },
        ),
        migrations.CreateModel(
            name="DocumentParseResult",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=quotation.models._uuid,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("parser_type", models.CharField(max_length=40)),
                (
                    "parse_status",
                    models.CharField(default="success", max_length=20),
                ),
                ("parsed_json", models.JSONField()),
                ("error_message", models.TextField(blank=True, null=True)),
                ("parsed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parse_result",
                        to="quotation.documentasset",
                    ),
                ),
            ],
            options={
                "db_table": "document_parse_results",
            },
        ),
        migrations.CreateModel(
            name="FeishuConnection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=quotation.models._uuid,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_email",
                    models.CharField(
                        db_index=True, max_length=255, unique=True
                    ),
                ),
                (
                    "feishu_open_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "feishu_union_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "feishu_user_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("access_token", models.TextField(blank=True, default="")),
                ("refresh_token", models.TextField(blank=True, default="")),
                (
                    "token_type",
                    models.CharField(default="Bearer", max_length=40),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("scope", models.TextField(blank=True, default="")),
                (
                    "preferred_folder_token",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "preferred_folder_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feishu_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "feishu_connections",
            },
        ),
        migrations.AddField(
            model_name="documentasset",
            name="quotation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="quotation.quotation",
            ),
        ),
        migrations.CreateModel(
            name="SyncJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=quotation.models._uuid,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("upload", "upload"),
                            ("pull", "pull"),
                            ("parse", "parse"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("running", "running"),
                            ("success", "success"),
                            ("failed", "failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payload_json", models.JSONField(blank=True, null=True)),
                ("result_json", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quotation.documentasset",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quotation.quotation",
                    ),
                ),
            ],
            options={
                "db_table": "sync_jobs",
            },
        ),
        migrations.CreateModel(
            name="QuotationItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=quotation.models._uuid,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("line_no", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Software", "Software"),
                            ("Service", "Service"),
                            ("Other", "Other"),
                        ],
                        default="Software",
                        max_length=20,
                    ),
                ),
                (
                    "item_id",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18
                    ),
                ),
                (
                    "list_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5
                    ),
                ),
                (
                    "net_unit_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18
                    ),
                ),
                (
                    "extended_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="quotation.quotation",
                    ),
                ),
            ],
            options={
                "db_table": "quotation_items",
                "ordering": ["line_no"],
                "unique_together": {("quotation", "line_no")},
            },
        ),
        migrations.CreateModel(
            name="QuotationVersion",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=quotation.models._uuid,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_no", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("generated", "generated"),
                            ("cancelled", "cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("snapshot_json", models.JSONField()),
                (
                    "operator_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="quotation.quotation",
                    ),
                ),
            ],
            options={
                "db_table": "quotation_versions",
                "ordering": ["version_no"],
                "unique_together": {("quotation", "version_no")},
            },
        ),
    ]
