# Generated by Django 5.1.15 on 2026-07-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("generated", "generated"),
                    ("uploaded", "uploaded"),
                    ("cancelled", "cancelled"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="quotationversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("generated", "generated"),
                    ("uploaded", "uploaded"),
                    ("cancelled", "cancelled"),
                ],
                max_length=20,
            ),
        ),
    ]
