# Generated by Django 5.1.15 on 2026-07-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "quotation",
            "0002_alter_quotation_status_alter_quotationversion_status",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="documentasset",
            name="feishu_url",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
