# Generated by Django 5.1.4 on 2026-07-15 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotation", "0010_encrypt_feishu_tokens"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserQuotationCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "catalog_version",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("initialized", models.BooleanField(default=False)),
                ("products", models.JSONField(blank=True, default=list)),
                ("services", models.JSONField(blank=True, default=list)),
                ("discounts", models.JSONField(blank=True, default=list)),
                ("product_lines", models.JSONField(blank=True, default=list)),
                ("payment_terms", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotation_catalog",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "quotation_user_catalogs",
            },
        ),
    ]
