# Generated by Django 5.1.4 on 2026-07-23 08:59

import django.db.models.deletion
import django.utils.timezone
import quotation.models
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def mark_document_imports(apps, schema_editor):
    quotation = apps.get_model("quotation", "Quotation")
    quotation.objects.filter(document_parse_results__isnull=False).update(
        source_type="document_import"
    )


def backfill_source_quote_numbers(apps, schema_editor):
    quotation = apps.get_model("quotation", "Quotation")
    for item in quotation.objects.filter(source_type="document_import"):
        item.source_quote_no = item.quote_no
        item.save(update_fields=["source_quote_no"])


def consolidate_feishu_assets(apps, schema_editor):
    document_asset = apps.get_model("quotation", "DocumentAsset")
    parse_result = apps.get_model("quotation", "DocumentParseResult")
    quotation = apps.get_model("quotation", "Quotation")
    sync_job = apps.get_model("quotation", "SyncJob")
    duplicate_tokens = (
        document_asset.objects.filter(
            source="feishu",
            feishu_file_token__isnull=False,
        )
        .exclude(feishu_file_token="")
        .values("feishu_file_token")
        .annotate(asset_count=Count("id"))
        .filter(asset_count__gt=1)
        .values_list("feishu_file_token", flat=True)
    )
    status_rank = {
        "not_quotation": 6,
        "confirmed": 5,
        "ready": 4,
        "review_required": 3,
        "running": 2,
        "failed": 1,
    }
    for token in list(duplicate_tokens):
        assets = list(
            document_asset.objects.filter(
                source="feishu",
                feishu_file_token=token,
            ).order_by("created_at", "id")
        )

        def priority(asset):
            """Prefer the latest final parse for one remote token."""
            result = (
                parse_result.objects.filter(asset_id=asset.id)
                .order_by("-created_at", "-id")
                .first()
            )
            return (
                status_rank.get(result.status if result else "", 0),
                bool(asset.quotation_id),
                asset.created_at,
                asset.id,
            )

        keeper = max(assets, key=priority)
        for duplicate in assets:
            if duplicate.id == keeper.id:
                continue
            if not keeper.quotation_id and duplicate.quotation_id:
                keeper.quotation_id = duplicate.quotation_id
                keeper.save(update_fields=["quotation"])
            sync_job.objects.filter(asset_id=duplicate.id).update(
                asset_id=keeper.id
            )
            duplicate.delete()

    orphan_ids = list(
        quotation.objects.filter(source_type="document_import")
        .annotate(document_count=Count("documents"))
        .filter(document_count=0)
        .values_list("id", flat=True)
    )
    quotation.objects.filter(id__in=orphan_ids).delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('quotation', '0011_userquotationcatalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentasset',
            name='feishu_folder_path',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='documentasset',
            name='feishu_folder_token',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_sync_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='scope_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='trace_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_email', models.CharField(blank=True, default='', max_length=255)),
                ('actor_name', models.CharField(blank=True, default='', max_length=255)),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('task', 'Task')], db_index=True, default='user', max_length=20)),
                ('actor_role_snapshot', models.CharField(blank=True, default='', max_length=100)),
                ('impersonator_id', models.CharField(blank=True, default='', max_length=100)),
                ('event_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('module', models.CharField(db_index=True, max_length=50)),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('result', models.CharField(choices=[('succeeded', 'Succeeded'), ('denied', 'Denied'), ('failed', 'Failed')], db_index=True, max_length=20)),
                ('target_type', models.CharField(blank=True, default='', max_length=100)),
                ('target_id', models.CharField(blank=True, default='', max_length=100)),
                ('target_label', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.CharField(blank=True, default='', max_length=500)),
                ('before_summary', models.JSONField(blank=True, default=dict)),
                ('after_summary', models.JSONField(blank=True, default=dict)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, default='', max_length=100)),
                ('trace_id', models.CharField(blank=True, default='', max_length=100)),
                ('reason_code', models.CharField(blank=True, default='', max_length=100)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=20)),
                ('workspace_id', models.CharField(blank=True, default='', max_length=100)),
                ('quotation_id_snapshot', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('document_id_snapshot', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('storage_connection_id', models.CharField(blank=True, default='', max_length=100)),
                ('source_organization_id', models.CharField(blank=True, default='', max_length=100)),
                ('target_organization_id', models.CharField(blank=True, default='', max_length=100)),
                ('sync_job_id', models.CharField(blank=True, default='', max_length=100)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quotation_audit_events',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentReplica',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=quotation.models._uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('remote_file_token', models.CharField(blank=True, default='', max_length=255)),
                ('remote_url', models.URLField(blank=True, default='', max_length=512)),
                ('folder_token', models.CharField(blank=True, default='', max_length=255)),
                ('folder_path', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('failed', 'Failed'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('error_summary', models.CharField(blank=True, default='', max_length=500)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replicas', to='quotation.documentasset')),
            ],
            options={
                'db_table': 'quotation_document_replicas',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='syncjob',
            name='replica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_jobs', to='quotation.documentreplica'),
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rule', models.CharField(db_index=True, max_length=80)),
                ('severity', models.CharField(choices=[('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('false_positive', 'False positive')], db_index=True, default='open', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('recommendation', models.TextField(blank=True, default='')),
                ('runbook', models.TextField(blank=True, default='')),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('threshold', models.PositiveIntegerField(default=1)),
                ('window_minutes', models.PositiveIntegerField(default=1)),
                ('subject_key', models.CharField(db_index=True, max_length=255)),
                ('subject_email', models.CharField(blank=True, default='', max_length=255)),
                ('subject_name', models.CharField(blank=True, default='', max_length=255)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('subject_user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('trigger_count', models.PositiveIntegerField(default=1)),
                ('first_detected_at', models.DateTimeField(db_index=True)),
                ('last_detected_at', models.DateTimeField(db_index=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, choices=[('authorized_activity', 'Authorized business activity'), ('policy_violation', 'Policy violation'), ('false_positive', 'False positive'), ('other', 'Other')], default='', max_length=40)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('notify_affected_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_quotation_security_alerts', to=settings.AUTH_USER_MODEL)),
                ('evidence_events', models.ManyToManyField(blank=True, related_name='security_alerts', to='quotation.auditevent')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_quotation_security_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quotation_security_alerts',
                'ordering': ['-last_detected_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StorageConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=quotation.models._uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('provider', models.CharField(db_index=True, default='feishu', max_length=40)),
                ('display_name', models.CharField(max_length=255)),
                ('external_tenant_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('auth_mode', models.CharField(choices=[('tenant_app', 'Tenant application'), ('managed_account', 'Managed service account')], default='tenant_app', max_length=40)),
                ('app_id', models.CharField(blank=True, default='', max_length=255)),
                ('app_secret', models.TextField(blank=True, default='')),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('error', 'Error')], db_index=True, default='active', max_length=20)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('last_health_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_health_error_code', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'quotation_storage_connections',
                'ordering': ['display_name', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_tenant_id', ''), _negated=True), fields=('provider', 'external_tenant_id'), name='quotation_storage_provider_tenant_unique')],
            },
        ),
        migrations.AddField(
            model_name='documentreplica',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_replicas', to='quotation.storageconnection'),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='storage_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_jobs', to='quotation.storageconnection'),
        ),
        migrations.CreateModel(
            name='StorageMount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=quotation.models._uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('scope_key', models.CharField(blank=True, default='', max_length=100)),
                ('purpose', models.CharField(choices=[('quotation_archive', 'Quotation archive'), ('quotation_share', 'Quotation share')], db_index=True, default='quotation_archive', max_length=50)),
                ('document_type', models.CharField(blank=True, default='', max_length=40)),
                ('root_folder_token', models.CharField(max_length=255)),
                ('root_folder_name', models.CharField(blank=True, default='', max_length=255)),
                ('path_template', models.CharField(blank=True, default='{year}/{product_line}/{quote_no}', max_length=500)),
                ('conflict_policy', models.CharField(choices=[('rename', 'Rename'), ('reuse', 'Reuse')], default='rename', max_length=20)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mounts', to='quotation.storageconnection')),
            ],
            options={
                'db_table': 'quotation_storage_mounts',
                'ordering': ['scope_key', 'purpose', 'document_type', 'id'],
            },
        ),
        migrations.AddField(
            model_name='documentreplica',
            name='mount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_replicas', to='quotation.storagemount'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['module', 'action', 'created_at'], name='quotation_a_module_024a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor', 'created_at'], name='quotation_a_actor_i_397c44_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['target_type', 'target_id'], name='quotation_a_target__3cedb0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['request_id', 'created_at'], name='quotation_a_request_80f6da_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['result', 'risk_level', 'created_at'], name='quotation_a_result_895550_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['status', 'severity'], name='quotation_s_status_17d6a6_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['rule', 'subject_key', 'status'], name='quotation_s_rule_345fce_idx'),
        ),
        migrations.AddConstraint(
            model_name='storagemount',
            constraint=models.UniqueConstraint(fields=('scope_key', 'purpose', 'document_type', 'connection'), name='quotation_storage_mount_route_unique'),
        ),
        migrations.AddConstraint(
            model_name='documentreplica',
            constraint=models.UniqueConstraint(fields=('asset', 'connection', 'version'), name='quotation_replica_version_unique'),
        ),
        migrations.RenameField(
            model_name='documentparseresult',
            old_name='parser_type',
            new_name='parser_name',
        ),
        migrations.RenameField(
            model_name='documentparseresult',
            old_name='parse_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='documentparseresult',
            old_name='parsed_json',
            new_name='normalized_json',
        ),
        migrations.RenameField(
            model_name='documentparseresult',
            old_name='parsed_at',
            new_name='created_at',
        ),
        migrations.AlterModelOptions(
            name='documentparseresult',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterField(
            model_name='documentparseresult',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parse_results', to='quotation.documentasset'),
        ),
        migrations.AlterField(
            model_name='documentparseresult',
            name='normalized_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='documentparseresult',
            name='parser_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='documentparseresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('review_required', 'Review required'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('superseded', 'Superseded')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='documentparseresult',
            name='confidence',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='documentparseresult',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentparseresult',
            name='content_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentparseresult',
            name='created_by_email',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='documentparseresult',
            name='field_confidence_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='documentparseresult',
            name='parser_version',
            field=models.CharField(default='legacy', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentparseresult',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_parse_results', to='quotation.quotation'),
        ),
        migrations.AddField(
            model_name='documentparseresult',
            name='source_totals_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='documentparseresult',
            name='sync_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parse_result', to='quotation.syncjob'),
        ),
        migrations.AddField(
            model_name='documentparseresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentparseresult',
            name='validation_errors_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='documentparseresult',
            name='validation_warnings_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name='documentparseresult',
            constraint=models.UniqueConstraint(fields=('asset', 'content_hash', 'parser_version'), name='quotation_document_parse_result_unique'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('document_import', 'Document import')], db_index=True, default='manual', max_length=30),
        ),
        migrations.RunPython(
            code=mark_document_imports,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='quotation',
            name='source_quote_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.RunPython(
            code=backfill_source_quote_numbers,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='syncjob',
            name='job_type',
            field=models.CharField(choices=[('upload', 'upload'), ('pull', 'pull'), ('parse', 'parse'), ('ocr', 'ocr')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='duration_ms',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='stage',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='syncjob',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('queued', 'queued'), ('running', 'running'), ('retrying', 'retrying'), ('success', 'success'), ('failed', 'failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentparseresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('review_required', 'Review required'), ('confirmed', 'Confirmed'), ('not_quotation', 'Not quotation'), ('failed', 'Failed'), ('superseded', 'Superseded')], db_index=True, default='pending', max_length=30),
        ),
        migrations.RunPython(
            code=consolidate_feishu_assets,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='documentasset',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'feishu'), ('feishu_file_token__isnull', False), models.Q(('feishu_file_token', ''), _negated=True)), fields=('source', 'feishu_file_token'), name='quotation_feishu_asset_token_unique'),
        ),
    ]
