# Generated by Django 5.1.4 on 2026-08-18 06:41

import django.db.models.deletion
import quotation.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotation", "0020_exportjob_archive_folder_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeishuFileSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=quotation.models._uuid,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "remote_file_token",
                    models.CharField(max_length=255, unique=True),
                ),
                (
                    "folder_token",
                    models.CharField(db_index=True, max_length=255),
                ),
                ("folder_path", models.JSONField(blank=True, default=list)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                (
                    "modified_time",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "metadata_fingerprint",
                    models.CharField(db_index=True, max_length=64),
                ),
                (
                    "deleted_in_feishu",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feishu_snapshots",
                        to="quotation.documentasset",
                    ),
                ),
            ],
            options={
                "db_table": "quotation_feishu_file_snapshots",
                "ordering": ["file_name", "remote_file_token"],
            },
        ),
        migrations.CreateModel(
            name="FeishuSyncState",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=quotation.models._uuid,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "root_folder_token",
                    models.CharField(db_index=True, max_length=255),
                ),
                (
                    "root_folder_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("synced", "Synced"),
                            ("syncing", "Syncing"),
                            ("has_diff", "Has differences"),
                            ("failed", "Failed"),
                            ("permission", "Permission denied"),
                            ("missing", "Directory missing"),
                        ],
                        db_index=True,
                        default="synced",
                        max_length=24,
                    ),
                ),
                (
                    "last_local_sync_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "latest_feishu_check_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("difference_count", models.PositiveIntegerField(default=0)),
                (
                    "error_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feishu_sync_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "storage_connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feishu_sync_states",
                        to="quotation.storageconnection",
                    ),
                ),
            ],
            options={
                "db_table": "quotation_feishu_sync_states",
                "ordering": ["root_folder_name", "root_folder_token", "id"],
            },
        ),
        migrations.CreateModel(
            name="FeishuSyncDifference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=quotation.models._uuid,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "difference_type",
                    models.CharField(
                        choices=[
                            ("added", "Added"),
                            ("deleted", "Deleted"),
                            ("moved", "Moved"),
                            ("renamed", "Renamed"),
                            ("modified", "Modified"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("detected", "Detected"),
                            ("applied", "Applied"),
                            ("pending_confirmation", "Pending confirmation"),
                            ("failed", "Failed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="detected",
                        max_length=24,
                    ),
                ),
                (
                    "file_token",
                    models.CharField(db_index=True, max_length=255),
                ),
                (
                    "previous_metadata",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "current_metadata",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="differences",
                        to="quotation.feishufilesnapshot",
                    ),
                ),
                (
                    "sync_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feishu_differences",
                        to="quotation.syncjob",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="differences",
                        to="quotation.feishusyncstate",
                    ),
                ),
            ],
            options={
                "db_table": "quotation_feishu_sync_differences",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="feishufilesnapshot",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_snapshots",
                to="quotation.feishusyncstate",
            ),
        ),
        migrations.AddIndex(
            model_name="feishusyncstate",
            index=models.Index(
                fields=["requested_by", "status", "-updated_at"],
                name="quote_fsync_user_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="feishusyncdifference",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sync_job__isnull", False)),
                fields=("sync_job", "file_token", "difference_type"),
                name="quote_fdiff_job_file_type_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="feishufilesnapshot",
            index=models.Index(
                fields=["state", "deleted_in_feishu", "folder_token"],
                name="quote_fsnap_state_deleted",
            ),
        ),
    ]
