# Generated by Django 5.1.4 on 2026-08-14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quotation", "0021_document_lifecycle"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotationMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("quotation_admin", "Quotation administrator"),
                            ("quotation_user", "Quotation user"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_quotation_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotation_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "quotation_memberships",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="quotation_member_user_active",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(is_active=True),
                        fields=("user",),
                        name="quotation_membership_active_user_unique",
                    ),
                ],
            },
        ),
    ]
