# Generated by Django 5.1.4 on 2026-08-14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quotation", "0022_quotation_membership"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotationViewPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("folder", "Feishu folder"),
                            ("document", "Feishu document"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "folder_token",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                    ),
                ),
                (
                    "folder_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotation_view_permissions",
                        to="quotation.documentasset",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="granted_quotation_view_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotation_view_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "quotation_view_permissions",
                "constraints": [
                    models.UniqueConstraint(
                        condition=(
                            models.Q(
                                ("is_active", True),
                                ("target_type", "folder"),
                            )
                            & ~models.Q(folder_token="")
                        ),
                        fields=("user", "target_type", "folder_token"),
                        name="quotation_active_folder_view_unique",
                    ),
                    models.UniqueConstraint(
                        condition=(
                            models.Q(
                                ("is_active", True),
                                ("target_type", "document"),
                            )
                            & models.Q(document__isnull=False)
                        ),
                        fields=("user", "target_type", "document"),
                        name="quotation_active_document_view_unique",
                    ),
                ],
            },
        ),
    ]
