# Generated by Django 5.1.4 on 2026-08-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "quotation",
            "0024_feishufilesnapshot_feishusyncstate_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotationUploadPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("folder_token", models.CharField(max_length=255)),
                (
                    "folder_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name=("granted_quotation_upload_permissions"),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotation_upload_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "quotation_upload_permissions",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active", "expires_at"],
                        name="quotation_upload_user_active",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("user", "folder_token"),
                        name="quotation_active_folder_upload_unique",
                    ),
                ],
            },
        ),
    ]
