# Generated by Django 5.1.4 on 2026-08-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quotation", "0025_quotation_upload_permission"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotationAccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("folder_view", "Folder view"),
                            ("document_view", "Document view"),
                            ("folder_upload", "Folder upload"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "folder_token",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "folder_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "document_id_snapshot",
                    models.CharField(blank=True, default="", max_length=36),
                ),
                (
                    "document_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True, default="")),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_access_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotation_access_requests",
                        to="quotation.documentasset",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_quotation_access_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "upload_permission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_access_requests",
                        to="quotation.quotationuploadpermission",
                    ),
                ),
                (
                    "view_permission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_access_requests",
                        to="quotation.quotationviewpermission",
                    ),
                ),
            ],
            options={
                "db_table": "quotation_access_requests",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["applicant", "status", "-created_at"],
                        name="quotation_request_app_status",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="quotation_request_status_time",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=(
                            models.Q(("status", "pending"))
                            & ~models.Q(("folder_token", ""))
                        ),
                        fields=(
                            "applicant",
                            "request_type",
                            "folder_token",
                        ),
                        name=("quotation_pending_folder_request_unique"),
                    ),
                    models.UniqueConstraint(
                        condition=(
                            models.Q(("status", "pending"))
                            & ~models.Q(("document_id_snapshot", ""))
                        ),
                        fields=(
                            "applicant",
                            "request_type",
                            "document_id_snapshot",
                        ),
                        name=("quotation_pending_document_request_unique"),
                    ),
                ],
            },
        ),
    ]
