# Generated by Django 5.1.4 on 2026-08-28

import re

from django.db import migrations, models


def _legacy_numbering_mode(quotation):
    """Infer whether a legacy draft number was an automatic preview."""
    quote_date = quotation.quote_date
    base = (
        f"{quotation.product_line}{quote_date.day:02d}"
        f"{quote_date.month:02d}{quote_date.year % 100:02d}"
    )
    pattern = rf"^{re.escape(base)}(?:\.[0-9]+)?$"
    return (
        "auto"
        if re.fullmatch(pattern, quotation.quote_no or "")
        else "custom"
    )


def move_legacy_draft_numbers(apps, schema_editor):
    """Move persisted draft numbers into the non-formal preview field."""
    quotation_model = apps.get_model("quotation", "Quotation")
    for quotation in quotation_model.objects.filter(status="draft"):
        legacy_quote_no = quotation.quote_no or ""
        quotation.draft_quote_no = legacy_quote_no
        quotation.numbering_mode = _legacy_numbering_mode(quotation)
        quotation.quote_no = None
        quotation.save(
            update_fields=[
                "draft_quote_no",
                "numbering_mode",
                "quote_no",
            ]
        )


def restore_legacy_draft_numbers(apps, schema_editor):
    """Restore preview numbers when reversing this migration."""
    quotation_model = apps.get_model("quotation", "Quotation")
    for quotation in quotation_model.objects.filter(
        status="draft",
        quote_no__isnull=True,
    ):
        if quotation.draft_quote_no:
            quotation.quote_no = quotation.draft_quote_no
            quotation.save(update_fields=["quote_no"])


class Migration(migrations.Migration):
    dependencies = [
        ("quotation", "0026_quotation_access_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="draft_quote_no",
            field=models.CharField(
                blank=True,
                default="",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="numbering_mode",
            field=models.CharField(
                choices=[("auto", "auto"), ("custom", "custom")],
                default="auto",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="quote_no",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=120,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(
            move_legacy_draft_numbers,
            restore_legacy_draft_numbers,
        ),
    ]
