# Generated by Django 5.1.4 on 2026-09-15 06:04

import django.db.models.deletion
import invoice.models
from django.conf import settings
from django.db import migrations, models


def migrate_invoice_roles(apps, schema_editor):
    """Collapse the legacy access roles into the two current roles."""
    grant_model = apps.get_model("invoice", "InvoiceAccessGrant")
    grant_model.objects.filter(role__in=["viewer", "operator"]).update(
        role="invoice_user"
    )
    grant_model.objects.filter(role="manager").update(role="invoice_admin")


def restore_invoice_roles(apps, schema_editor):
    """Restore the closest legacy role names when migrating backwards."""
    grant_model = apps.get_model("invoice", "InvoiceAccessGrant")
    grant_model.objects.filter(role="invoice_user").update(role="operator")
    grant_model.objects.filter(role="invoice_admin").update(role="manager")

class Migration(migrations.Migration):

    replaces = [('invoice', '0001_initial'), ('invoice', '0002_invoice_commercial_document_fields'), ('invoice', '0003_invoicedocument_purpose'), ('invoice', '0004_invoiceaccessgrant'), ('invoice', '0005_invoice_numbering'), ('invoice', '0006_invoice_access_role'), ('invoice', '0007_invoice_access_two_roles'), ('invoice', '0008_invoice_feishu_sync'), ('invoice', '0009_invoice_document_classification'), ('invoice', '0010_invoice_ledger_document_kind'), ('invoice', '0011_invoice_customer_contacts'), ('invoice', '0012_invoice_product_line_numbering'), ('invoice', '0013_invoice_customer_contact_phone'), ('invoice', '0014_invoice_document_feishu_ownership'), ('invoice', '0015_invoice_revision')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(default=invoice.models._uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(db_index=True, max_length=120)),
                ('invoice_date', models.DateField(db_index=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('void', 'Void'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('pdf_upload', 'PDF upload'), ('feishu', 'Feishu')], db_index=True, default='manual', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('seller_name', models.CharField(blank=True, default='', max_length=255)),
                ('seller_tax_id', models.CharField(blank=True, default='', max_length=120)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_tax_id', models.CharField(blank=True, default='', max_length=120)),
                ('region', models.CharField(blank=True, default='', max_length=120)),
                ('sales_owner', models.CharField(blank=True, default='', max_length=255)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-invoice_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceDocument',
            fields=[
                ('id', models.CharField(default=invoice.models._uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image')], default='pdf', max_length=20)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_invoice_documents', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='invoice.invoice')),
            ],
            options={
                'db_table': 'invoice_documents',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.CharField(default=invoice.models._uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('line_no', models.PositiveIntegerField()),
                ('product_code', models.CharField(blank=True, default='', max_length=120)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.invoice')),
            ],
            options={
                'db_table': 'invoice_items',
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceParseResult',
            fields=[
                ('id', models.CharField(default=invoice.models._uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('parser_name', models.CharField(max_length=120)),
                ('parser_version', models.CharField(max_length=40)),
                ('content_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('review_required', 'Review required'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('normalized_json', models.JSONField(default=dict)),
                ('field_confidence_json', models.JSONField(default=dict)),
                ('validation_errors_json', models.JSONField(default=list)),
                ('validation_warnings_json', models.JSONField(default=list)),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('created_by_email', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parse_results', to='invoice.invoicedocument')),
            ],
            options={
                'db_table': 'invoice_parse_results',
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['currency', 'status', 'invoice_date'], name='invoice_dash_curr_stat_date'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer_name', 'invoice_date'], name='invoice_customer_date'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['region', 'invoice_date'], name='invoice_region_date'),
        ),
        migrations.AddIndex(
            model_name='invoicedocument',
            index=models.Index(fields=['status', 'created_at'], name='invoice_doc_status_created'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['product_name', 'invoice'], name='invoice_item_product'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.UniqueConstraint(fields=('invoice', 'line_no'), name='invoice_item_line_unique'),
        ),
        migrations.AddIndex(
            model_name='invoiceparseresult',
            index=models.Index(fields=['document', 'status'], name='invoice_parse_doc_status'),
        ),
        migrations.AddConstraint(
            model_name='invoiceparseresult',
            constraint=models.UniqueConstraint(fields=('document', 'content_hash', 'parser_version'), name='invoice_parse_content_version_unique'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='additional_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_branch_code',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_code',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_swift_code',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issuer_signature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_terms',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_order_no',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='invoice',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='remittance_instruction',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_website',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='signatory_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='invoice',
            name='signatory_title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='invoicedocument',
            name='purpose',
            field=models.CharField(choices=[('source', 'Source'), ('issued', 'Issued invoice')], db_index=True, default='source', max_length=20),
        ),
        migrations.CreateModel(
            name='InvoiceNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=6, unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'invoice_number_sequences',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='numbering_mode',
            field=models.CharField(choices=[('auto', 'Automatic'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.CreateModel(
            name='InvoiceAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_invoice_access', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_access_grants', to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('operator', 'Operator'), ('manager', 'Manager')], default='manager', max_length=20)),
            ],
            options={
                'db_table': 'invoice_access_grants',
                'indexes': [models.Index(fields=['user', 'is_active', 'expires_at'], name='invoice_access_user_active')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='invoice_active_access_user_unique')],
            },
        ),
        migrations.RunPython(
            code=migrate_invoice_roles,
            reverse_code=restore_invoice_roles,
        ),
        migrations.AlterField(
            model_name='invoiceaccessgrant',
            name='role',
            field=models.CharField(choices=[('invoice_user', 'Invoice user'), ('invoice_admin', 'Invoice administrator')], default='invoice_admin', max_length=20),
        ),
        migrations.AddField(
            model_name='invoicedocument',
            name='feishu_file_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoicedocument',
            name='feishu_folder_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoicedocument',
            name='feishu_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddConstraint(
            model_name='invoicedocument',
            constraint=models.UniqueConstraint(condition=models.Q(('feishu_file_token', ''), _negated=True), fields=('feishu_file_token',), name='invoice_document_feishu_token_unique'),
        ),
        migrations.CreateModel(
            name='InvoiceSyncRun',
            fields=[
                ('id', models.CharField(default=invoice.models._uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('periodic', 'Periodic')], default='manual', max_length=20)),
                ('discovered_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('reused_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_sync_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoice_sync_runs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='invoicedocument',
            name='purpose',
            field=models.CharField(choices=[('source', 'Source'), ('supporting', 'Supporting document'), ('issued', 'Issued invoice')], db_index=True, default='source', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceparseresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('review_required', 'Review required'), ('confirmed', 'Confirmed'), ('not_invoice', 'Not an invoice'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='invoice',
            name='document_kind',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('delivery_note', 'Delivery note'), ('withholding_tax', 'Withholding tax'), ('proforma_invoice', 'Proforma invoice'), ('refund', 'Refund')], db_index=True, default='invoice', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('document_kind', 'invoice'), models.Q(('invoice_no', ''), _negated=True)), fields=('invoice_no',), name='invoice_formal_number_unique'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['document_kind', 'status', 'invoice_date'], name='invoice_kind_status_date'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_contact_person',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='invoicenumbersequence',
            name='period',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='product_line',
            field=models.CharField(default='BDR', max_length=40),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_contact_phone',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='invoicedocument',
            name='feishu_file_owned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicedocument',
            name='feishu_owner_connection_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='invoice',
            name='revision_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='InvoiceRevision',
            fields=[
                ('id', models.CharField(default=invoice.models._uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('revision_no', models.PositiveIntegerField()),
                ('invoice_no', models.CharField(max_length=120)),
                ('snapshot_json', models.JSONField(default=dict)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_revisions', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='invoice.invoice')),
            ],
            options={
                'db_table': 'invoice_revisions',
                'ordering': ['-revision_no', '-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('invoice', 'revision_no'), name='invoice_revision_no_unique')],
            },
        ),
    ]
